vmware/vcd-cli

vcd_cli/role.py
vcd_cli/user.py
vcd_cli/vcd.py

* Commands to create local user and list roles in an org
* added default values to create_user params
Changed formatting after running flake8
* Made the imports in alphabetical order.
* Refactored get_role in SDK to return a single role instead of a list of role.
Role does not exist error message is moved to SDK

(Sprint-74) Commands to create local user and list roles in an org (#1)

---

vcd_cli/catalog.py

(pyvcloud) malakars-m01:pyvcloud malakars$ pwd
/Users/malakars/pyworkspace/pyvcloud
(pyvcloud) malakars-m01:pyvcloud malakars$ cd tests
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_catalog.TestCatalog.test_catalog_control_access_retrieval
/Users/malakars/.virtualenvs/pyvcloud/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
.
Ran 1 test in 0.435s
OK

VCDA-217: Retrieve access control settings of a catalog

---

vcd_cli/cluster.py

Testing done :
CLI command :
(vcd-cli) C:\code\vcd-cli>vcd cluster create -n net1 -N 2 -c 2 -m 1025 --ssh-key ssh-key.txt "aritra-test-cluster"
cse.log :
DEBUG    2017-11-29 08:14:08,615 container_service_extension.processor    process_request                      55  : request body: {"name": "aritra-test-cluster", "node_count": 2, "vdc": "vdc1", "cpu-count": "2", "memory": "1025", "network": "net1", "storage_profile": null, "ssh-key": "sample SSH key"}
Note : the command failed with an error stating 'not enough IP addresses' on the extension. But I believe it's not related to my changes.

Implementing new params for vcd cluster create command

---

vcd_cli/role.py

Ran pep8 code violation inspection.
-----------------
Sample command output
> vcd role list-rights 'vApp User'
name
---------------------------------
vApp Template: Checkout
UI Plugins: View
vApp: Snapshot Operations
vApp: Copy
vApp: Manage VM Password Settings
vApp Template / Media: View
vApp: Edit VM Properties
vApp: View VM metrics
vApp: Delete
vApp: Use Console
Disk: View Properties
vApp: Power Operations
vApp: Sharing
vApp: Edit Properties
vApp: Edit VM Network

Command to list rights for a given role in an Org

---

test-requirements.txt
vcd_cli/info.py
vcd_cli/utils.py
vcd_cli/vcd.py

Also exposing option to turn off colored output entirely.
Tested manually to delete a non existent independent disk,
Before fix : After error console text color became dark gray
After fix : After error console text color remained the same as the foreground color
Also checked that setting the environment variable USE_COLROED_OUTPUT to anything other than '1' lead to error messages being printed out in normal text color. If the environment variable is unset or set to '1' color RED is used to print error messages.
Tested the following scenarios
Environment variable USE_COLORED_OUPUT not set
------------------------------------------------------
vcd info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored …

Fixing text color issue after an error

---

CODE_OF_CONDUCT.md
ISSUE_REQUEST.md
PULL_REQUEST_TEMPLATE.md

Added files to fulfill GitHub community standards.  Code of conduct
adapted from VMware Clarity project.  PR and issue conventions are
derived from current practice.

Add code of conduct and PR/issue templates

---

vcd_cli/disk.py
vcd_cli/utils.py
vcd_cli/vapp.py

(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd disk list
id                                    name    owner      size        size_bytes  status    vms_attached
------------------------------------  ------  ---------  --------  ------------  --------  --------------
bea35db5-7c44-4d52-bbfd-1126162b8b50  disk1   org-admin  20 bytes            20  Resolved
efa4f7ea-62ba-415c-9427-c2a7d96a5ed3  disk1   org-admin  10 bytes            10  Resolved
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd disk info disk1
Usage: vcd disk info [OPTIONS] <name>
Error: Found multiple disks with name disk1, please identify disk via disk-id.
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd disk info id:bea35db5-7c44-4d52-bbfd-1126162b8b50
property        value
--------------  ------------------------------------
busSubType      lsilogic …

 VCDA-311 : Unifying argument 'name' and option 'id' for independent disk related commands

---

vcd_cli/network.py

* Implemened commands to create isolated OrgVDC networks.
* Ran yapf on network.py for formatting
Manual run the command,
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd network isolated create iso-net1 -d "Dummy description" -g 192.168.1.1 -n 255.255.255.0
networkCreateOrgVdcNetwork: Creating Network iso-net1(167f0b16-6122-4a29-8980-7062abe9dcb7)
networkCreateOrgVdcNetwork: Creating Network iso-net1(167f0b16-6122-4a29-8980-7062abe9dcb7)
task: bd8da4ca-0180-49d1-b335-f635681b8093, Created Network iso-net1(167f0b16-6122-4a29-8980-7062abe9dcb7), result: success
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/161)

VCDA-369: Implementing commands to create isolated OrgVDC networks.

---

vcd_cli/network.py

* Added command group 'external' to command group 'network'
* Added  new command list to command group 'external'
Manual testing of the command:
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd network external list
name
--------
ext-net1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/168)

VCDA-394: Adding command to list external networks.

---

README.md
docs/install.md

Added installation commands for Photon, vetted commands with current vcd-cli
version, cleaned up text, and added install.md reference in README.md.
Reviewers: @pacogomez @anusuyar @sompa @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/165)

VCDA-181: Clean up installation instructions for vcd-cli

---

vcd_cli/network.py

* Added commands to list and delete both direct networks and isolated org vdc networks.
Manual testing of commands
------
(vcd-cli) C:\code\vcd-cli\vcd_cli>vcd network direct list
name
[------]
dnet1
Dnet1
(vcd-cli) C:\code\vcd-cli\vcd_cli>vcd network direct delete dnet1
Are you sure you want to delete the OrgVdc Network? [y/N]: y
networkDelete: Deleting Network dnet1(3c3a916e-6601-4df5-84f0-804d2774757f)
task: 93732628-5b4f-45e2-ad10-9c8302b12e13, Deleted Network dnet1(3c3a916e-6601-4df5-84f0-804d2774757f), result: success
To test --force option, I attached the network to a vApp and tried to delete the network with and without the option --force
(vcd-cli) C:\code\vcd-cli\vcd_cli>vcd network direct delete Dnet1
Are you sure you want to delete the OrgVdc Network? [y/N]: y
Usage: vcd …

VCDA-395 and VCDA-396: Adding commands for listing and deleting org vdc networks 

---

vcd_cli/info.py

* Got rid of spurious help item related to catalog list
* Added line breaks between individual examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/177)

VCDA-470: Fixing help text for command vcd info

---

tests/tenant-onboard.sh
vcd_cli/pvdc.py

- Implemented list storage profiles by implementing vcd-cli command 'pvdc info name'
- Tested by tenant-onboard.sh 
property          value
----------------  -------------------------------------
cpu_capacity     units: MHz
total: 11024
allocation: 0
used: 0
overhead: 0
description        Generated Provider vDC
id                        1d9c86f4-7ca6-42f0-9f76-ffbb9441f62a
is_enabled          True
mem_capacity    units: MB
total: 6565
allocation: 0
used: 0
overhead: 0
name                   pvdc-2018-01-16-15-02-24.676
network_pools    pvdc-2018-01-16-15-02-24.676-VXLAN-NP
storage_profiles  Development
*
supported_hw      vmx-04
vmx-07
vmx-08
vmx-09
vmx-10
vmx-11
vdc_refs               acmevdc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

VCDA-441 list available storage profiles

---

vcd_cli/vapp.py
vcd_cli/vm.py

Includes cli commands for updating the cpu and memory of a VM.
- Only cli command for updating the cpu and memory of a VM.
- Added examples for the same in doc
Command : **vcd vm update -h**
```
Usage: vcd vm update [OPTIONS] <vapp-name> <vm-name>
Options:
--cpu <cpu>        Number of virtual CPUs to configure the VM.
--cores <cores>    Number of cores per socket.
--memory <memory>  Memory to configure the VM.
-h, --help         Show this message and exit.
```
Command : **vcd vm update sompa-vapp vAppTemplate2 --cpu 2 --memory 8**
```
Updating cpu (and core if specified) for the VM
vappUpdateVm: Updating Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c)
vappUpdateVm: Updating Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c)
task: …
```

 VCDA-410 & 411: VM commands to update cpu and memory of a Vm

---

vcd_cli/vapp.py

access_settings_to_dict conversion was originally present in the pyvcloud vapp.get_access_settings(). It was supposed to be moved to vcd-cli.  I removed it from get_access_settings(), but forgot to add it in vcd-cli
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/186)

Adding the missing access_settings_to_dict method in vcd-cli/vapp.py .

---

vcd_cli/amqp.py
vcd_cli/catalog.py
vcd_cli/disk.py
vcd_cli/extension.py
vcd_cli/gateway.py
vcd_cli/info.py
vcd_cli/netpool.py
vcd_cli/network.py
vcd_cli/org.py
vcd_cli/profile.py
vcd_cli/pvdc.py
vcd_cli/right.py
vcd_cli/role.py
vcd_cli/system.py
vcd_cli/task.py
vcd_cli/user.py
vcd_cli/utils.py
vcd_cli/vapp.py
vcd_cli/vc.py
vcd_cli/vdc.py
vcd_cli/vm.py

- restore session is now called just one time when needed
- added parameter to load vdc in use
- in the network commands, it validates that a vdc is selected
- fixes VCDA-286 to display any command help with no login required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/185)

VCDA-436: avoid unnecessary session restoration

---

vcd_cli/plugin.py
vcd_cli/profile.py
vcd_cli/profiles.py
vcd_cli/vapp.py

- added list/add/remove extension commands, under the profile sub-command
- added warning when a module with extension commands can't be loaded
- added profile info command
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/187)

VCDA-417: commands to manage extension commands

---

vcd_cli/browsercookie/__init__.py

- add support in browsercookie for multiple keyring backends, when using session id from chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/188)

VCDA-510: support multiple keyring backends in browsercookie

---

setup.py
vcd_cli/amqp.py
vcd_cli/catalog.py
vcd_cli/disk.py
vcd_cli/extension.py
vcd_cli/gateway.py
vcd_cli/info.py
vcd_cli/login.py
vcd_cli/netpool.py
vcd_cli/network.py
vcd_cli/org.py
vcd_cli/profile.py
vcd_cli/profiles.py
vcd_cli/pvdc.py
vcd_cli/right.py
vcd_cli/role.py
vcd_cli/search.py
vcd_cli/system.py
vcd_cli/task.py
vcd_cli/user.py
vcd_cli/utils.py
vcd_cli/vapp.py
vcd_cli/vcd.py
vcd_cli/vdc.py
vcd_cli/vm.py

Updated .py file copyright dates to most recent commit and extended back
in one case to first known commit from git log. Copyright dates follow
earliest-latest date convention.
Reviewers: @sahithi, @anusuyar, @pacogomez, @rdbwebster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/189)

VCDA-454: Updated copyrights for release

---

vcd_cli/vdc.py

Some commands like vcd vdc list/use were failing because we don't do case-insensitive org name comparison.
This can happen when we create an Org with uppercase, say ORG1,
login in vcd-cli using lower case( org1) and then try to list the vdc in ORG1.
Since the org_name from the api does not match with the in_use_org we store in the profiles file, we get in the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/192)

VCDA-496: Fix org case insensitive issue

---

requirements.txt

Adjusted requirements.txt to force pycryptodome to be version 3.4.x, as
3.5.0 does not compile on Mac OS X.
Reviewers: @sompa, @sahithi, @rocknes, @anusuyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/197)

VCDA-532: Fix requirements.txt to avoid Mac OS X pycryptodome bug

---

docs/install.md

Same error + fix as my pyvcloud install.md PR today. Fixes the venv activation command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/202)

Same as pyvcloud PR - fix venv activation command

---

vcd_cli/org.py

Fixed org.py to instantiate pyvcloud System with required admin_resource
argument.  This appears to have been missed in an earlier pass to clean up
instantiation errors on the System class. 
Reviewers: @anusuyar, @sompa

Issue 215: Fixed bug in vcd org delete

---

vcd_cli/user.py
vcd_cli/utils.py

* Added logic in user creation command to throw appropriate exception if password length is not adequate.
* Also fixed a small case related issue in is_sysadmin() function.
Testing done: Ran command manually to see the exception in action.
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd user create test test "vApp Author"
Usage: vcd user create [OPTIONS] <user_name> <password> <role-name>
Error: Password must be atleast 6 characters long.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/217)

Added additional logic in user creation command to check password length

---

vcd_cli/catalog.py

Non admin users who are not owner of a catalog but has viewing rights, can't access the ACL of the catalog.  The command *vcd catalog info* disregards this limitation and tries to retreive the ACL of catalog for all users. This leads to an exception being raised, and such users can never use the command.
As a fix we omit catalog ACL details for users who can't access them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/225)

[VCDA-603] Fixed 'vcd catalog info' when user can't access ACL settings of the catalog.

---

vcd_cli/vc.py

- 'vcd vc attach..' prints success message even if the command fails. #229 (vcd-cli)
- 'vcd vc attach ..' option -e (enable isn't optional) #230 (vcd-cli)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/232)

fixed bug https://github.com/vmware/vcd-cli/issues/229 & #230

---

vcd_cli/profiles.py

Fix for CVE-2017-18342 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342
vcd-cli derives it's dependency on PyYAML from pyvcloud so no explicit action is required in vcd-cli to restrict PyYAML version.
Replaced instances of yaml.load() to yaml.safe_load().
Tried out vcd login command and it worked correctly, thus confirming that yaml.safe_load() hasn't caused any regressions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/233)

[VCDA-709] CVE-2017-18342 : Replace yaml.load() with yaml.safe_load()

---

vcd_cli/login.py

We were restricting the values of the flag -V (--version) to the above mentioned values. This stopped the user from specifying a newer api version viz 31.0.
As a fix we have removed the restriction.
Testing done: Tried the following command and it worked fine, the user was logged in
(vcd-cli) C:\code\vcd-cli>vcd login 10.150.200.112 system administrator -i -w -V 31.0
Password:
administrator logged in, org: 'system', vdc: ''
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/237)

[VCDA-727] Fixed login issue with custom version other than [27.0, 28.0, 29.0, 30.0]

---

vcd_cli/catalog.py
vcd_cli/info.py
vcd_cli/vapp.py

As a fallout of https://github.com/vmware/pyvcloud/pull/282, we need to make sure that we url encode filter values properly in vcd-cli.
Changed qfilter to equality_filter wherever possible, since equality_filter url-encodes the value properly.
Tested the following commands to make sure that no regressions were introduced
vcd catalog list <cat-name>
vcd info adminVApp <vapp-id>
vcd vapp list
vcd vapp list <vapp-name>
Also replaced hard-coded strings to their ResourceType enum counterpart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/239)

[VCDA-549] Fix query service to handle special characters in filter values

---

vcd_cli/login.py

Due to the way we were writing few booleans that control logging of requests to the profiles.yaml file, vcd-cli wasn't logging any backend requests. As a fix we made sure that the correct values are being written to profiles.yaml.
Ran few vcd-cli commands and made sure that all related REST calls were getting logged properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/242)

[VCDA-760] Fix logging of REST calls made on behalf of vcd-cli commands.

---

vcd_cli/extension.py
vcd_cli/utils.py

The real fix has been made in pyvcloud https://github.com/vmware/pyvcloud/pull/288 .
Removing some exception handling while writing message to click.echo() to let the real exception message bubble up.
Tested the vcd-cli commands 
vcd system extension list
vcd system extension info <bogus service>
and verified that after the change, proper error messages are displayed for both sys admin and non sys admin users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/243)

[VCDA-762] Fix confusing error message when non admin users invoke vcd system extension commands

---

requirements.txt

Updated requirements.txt to limit version of keyring module to 12.0.0. Latest version of keyring module is causing installation failure on linux machines.
Tested on Windows, Linux, Mac and made sure that installation + commands work fine on these systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/244)

[VCDA-756] Limit keyring version to 12.0.0 to avoid installation failures on linux.

---

requirements.txt
vcd_cli/browsercookie/__init__.py

The command was broken because 
1. one of the internal queries to the cookie sqllite file was using a wrong filed name viz secure while it should have been is_secure.
2. the module win32crypt required to decrypt cookie values on Windows was missing from our requirements list.
As a fix, the correct column name has been used in the query and a dependency on pywin32 (provides win32crypt module) has been added only for windows installations. the module doesn't exist for OSX or linux.
Also fixed flake8 errors in the file browsercookie\__init__.py
Testing done : On Windows and Mac, we installed a fresh copy of vcd-cli with the fix and made sure
1. the installation succeeded without any issue 
2. we were able to run the affected command without any errors.
--- …

[VCDA-761] Fix command vcd login session list chrome for Windows

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

[VP-1184, VP-1201] Provided command line support for convert to advanced gateway and enable distributed routing.
This will enable the command line support for:
1: Convert legacy gateway to advanced gateway
vcd gateway convert-to-advanced <name>
2: Enable distributed routing
vcd gateway enable-distributed-routing <gw_name> --enable/--disable
Testing Done: Added test case for both the use cases
@shashim22 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/260)

[VP-1184, VP-1201] Provided command line support for convert to advanced gateway and enable distributed routing

---

system_tests/extnet_tests.py
system_tests/run_system_tests.sh
vcd_cli/network.py

Implementation of create and delete external network commands.
Adding 'create' & 'delete' commands to 'external' group. External network can be created by command: 'vcd network external create [OPTIONS]'. It can be deleted by command: 'vcd network external delete '. 
Testing done:
Test cases for create and delete are added to a new test class, extnet_tests. 
@ckolovson @rocknes @rajeshk2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/257)

[VP-1147, VP-1148] : Implement commands to create and delete external networks.

---

system_tests/extnet_tests.py
vcd_cli/network.py

Implementation of update external network command.
Adding 'update' command to 'external' group. This command can be used to update name or description or both. Command to update is: 'vcd network external update --name --description '
Testing done:
Added a test case for update in extnet_tests. All tests in extnet_tests passes.
@rajeshk2013 @rocknes

[VP-1154] Update name and description of external network in VCD CLI

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

Added a new command 'info' as per the CLI design document.
IP allocations are displayed as one of the property of the gateway.
Example output:
(vcd-cli) C:\development\vcd-cli>vcd gateway info edge2
property                         value
external_network_ip_allocations  extnw3: ['10.10.10.2']
Testing done: ran gateway_tests successfully.
Output:
(vcd-cli) C:\development\vcd-cli\system_tests>python -m unittest gateway_tests.py
..........
Ran 10 tests in 262.436s
OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/267)

VP-1241 List external network IP allocations.

---

system_tests/extnet_tests.py
vcd_cli/network.py

Modifies an IP range of a subnet in an external network.
This will modify the exiting Ip Range of a subnet with the new IP Range.
Testing done: 
vcd-cli command : passed
-------------------------------
(vcd-cli) C:\dev-python-dnd\vcd-cli>vcd network external modify-ip-range ext -g 192.168.1.1 -i 192.168.1.12-192.168.1.22 -n 192.168.1.5-192.168.1.10
networkUpdateNetwork: Updating Network ext(02409fa5-6362-4d29-a500-8df1a0bdbefa)
task: 551e6bb8-76b7-4151-b7ed-1e34c4b0b28f, Updated Network ext(02409fa5-6362-4d29-a500-8df1a0bdbefa), result: success
Ip Range of a subnet modified successfully.
system-tests : passed

VP-1244: Modify an IP range of a subnet in external network

---

system_tests/base_config.yaml
system_tests/gateway_tests.py
vcd_cli/gateway.py

Added two commands in configure-external-network command group.
1. Add: adds an external network with the specified subnet and ip address.
2. Remove: removes an existing external network from the gateway.
Added corresponding test cases.
Testing done: ran gateway_tests succesfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/276)

VP-1253, VP-1254: configure external network for gateways.

---

system_tests/constants.py
system_tests/gateway_tests.py
system_tests/vdc_network_tests.py
vcd_cli/network.py

[VP-1429, VP-1430] Support added for create routed vdc network and delete of routed vdc network
Added CLI support for create and delete of routed vdc network
vcd network routed create <name> -g <gateway_name> --subnet 2.2.2.3/20
vcd network routed delete <name>
Testing Done: Added test case in vdc_routed_network.tests and executed them successfully
@chaitanya118 @pandeys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/278)

[VP-1429, VP-1430] Support added for create routed vdc network and delete of routed vdc network

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

VP-1250, VP-1291: Edit edge gateway name and gateway config ip settings
VP-1250: Edit edge gateway name
User can edit the gateway name eg : vcd gateway edit_gateway_name gateway1 --n gateway2
VP-1292: Edit gateway config ip settings
User can change the Config ip settings, enable/disable subnet participation 
eg: vcd gateway configure-ip-settings gateway1 --external-network
extNetwork --subnet-available 10.20.30.1/24 True 10.20.30.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/279)

VP-1250, VP-1291: Edit edge gateway name and gateway config ip settings

---

system_tests/vc_tests.py
vcd_cli/vc.py

VCD-CLI: List available portgroups in a vCenter
Testing done:
cli command :passed
(vcd-cli) C:\dev2-python-dnd\vcd-cli\system_tests>vcd vc list-available-port-groups vc1
property                      value
---------------------        -----------
available port-groups  TestbedPG1
DPortGroup1
DPortGroup2
DPortGroup3
DPortGroup4
test case: passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/281)

VP-1451: list available portgroups

---

system_tests/base_config.yaml
system_tests/gateway_tests.py
vcd_cli/gateway.py

VP-1295:Add sub-allocate ip pools to gateway
Adds new ip range present to the sub allocate pool of gateway.
Examples
vcd gateway sub-allocate-ip add gateway1
--external_network extNw1
--ip-range  10.10.10.20-10.10.10.30
Adds sub allocate ip pools to the edge gateway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/283)

VP-1295:Add sub-allocate ip pools to gateway

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

Edit gateway for Sub-Allocate IP Pools
User can edit the existing ip range present in the sub allocate pool of gateway.
For example :
vcd gateway sub-allocate-ip update gateway1
-e extNw1
--old-ip-range 10.10.10.20-10.10.10.30
--new-ip-range 10.10.10.40-10.10.10.50
Made changes to gateway.py and gateway_tests.py file and implemented edit_sub_allocated_ip_pools method in gateway.py file to achieve the functionality
Test cases are passing

VP-1297:Edit gateway for Sub-Allocate IP Pools

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

VP-1299:Remove sub allocate ip pool of the gateway
Removes the given IP ranges from the sub allocated pool, with these changes user would be able to delete the list of ip ranges from sub allocate ip pool of the gateway.
for example:
vcd gateway sub-allocate-ip remove gateway -e extNetwork -i 10.10.10.40-10.10.10.50
Implemented remove_sub_allocated_ip_pools in gateway.py to achieve the functionalities.
Test case is passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/287)

VP-1299:Remove suballocate ip pool of the gateway

---

vcd_cli/gateway.py

Before the fix, output for command vcd gateway -h shows configure_external_network in unix but configure-external-network in windows. Because of this, test cases which are posting command with '-' were succeeding in windows but failing in unix.
Same issue was with sub-allocate-ip sub-group.
After this fix, both group mentioned above will work with '-' and also show in 'vcd gateway -h' output.
Testing Done: Run the command where '-' is shown as the output and also executed the command without any error.
vcd gateway configure-external network -h
@guptaankit52 @chaitanya118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/288)

Under-score changed to Hyphen in windows resulting in gateway_tests failure in unix

---

system_tests/extnet_tests.py
system_tests/helpers/portgroup_helper.py
vcd_cli/network.py

Attaches a port group of same type to an external network using vcd-cli command.
Testing Done:
vcd- cli command:
C:\dev2-python-dnd\vcd-cli>vcd network external attach-port-group ext --vc-name vc2 --port-group DPortGroup
networkUpdateNetwork: Updating Network ext(01483b37-3919-4772-82d9-f9cbf6bea8c9)
task: dfcb4620-7adb-45c3-8d49-1d8df0fb8495, Updated Network ext(01483b37-3919-4772-82d9-f9cbf6bea8c9), result: success
Port group attached successfully.
unittest:
C:\dev2-python-dnd\vcd-cli\system_tests>python -m unittest extnet_tests.py
........
----------------------------------------------------------------------
Ran 8 tests in 151.751s
OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

VP-1258: Attach port groups to an external network

---

system_tests/extnet_tests.py
vcd_cli/network.py

VP 1446: [VCD-CLI] Delete an IP range of a subnet in external network
[VCD-CLI] Delete an IP range of a subnet in external network
This CLN contains code fro removing an IP range of a subnet in an
external network and it's test cases.
User can usel this command as:
vcd network external remove-ip-range <external_network_name>
--g <gateway-ip> --ip-range <startaddress-endaddress>
Testing done:
Test case for remove ip range is added to a test class,
extnet_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/290)

Delete ip range

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

VP-1490:Edit gateway for Configure Rate Limits
Updates gateway for Configure Rate Limits of gateway
Using this user would be able to update the Configure Rate Limits of gateway through command line:
e.g: vcd gateway configure-rate-limits update gateway1 --e extNw1 101.0 101.0
Testing done: Test cases passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/293)

VP-1490:Edit gateway for Configure Rate Limits

---

system_tests/vdc_network_tests.py
vcd_cli/network.py

User can add ip range for org vdc routed network. It has support for adding multiple ip range simultaneously.
Command: vcd network routed add-ip-ranges vdc_routed_nw --ip-range 6.6.2.1-6.6.2.10 --ip-range 6.6.3.1-6.6.3.10
Testing Done: Added test case for this functionality and executed them successfully.
@shashim22 @guptaankit52

[VP-1360]Edit routed network for Static IP pool under Network Specification (Add)

---

system_tests/vdc_network_tests.py
vcd_cli/network.py

User can list all the available org prov vdc routed network present in vdc.
Command: vcd network routed list
Testing Done: New tese case has been added and executed the complete test class successfully.
@shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/295)

VP-1355]List routed vdc networks

---

system_tests/extnet_tests.py
vcd_cli/network.py

VP 1269: [VCD-CLI] List associated edge gateways
[VCD-CLI] List associated edge gateways
This CLN contains code related to listing associated gateways. It also
test case related to the functionality.
User can call this command as:
vcd network external list-gateway <ext_net_name>
Testing done:
Test case for list associated gateways  is added to a test class,
extnet_tests.py

List gateways

---

system_tests/extnet_tests.py
vcd_cli/network.py

VP 1265: [VCD-CLI] List allocated IP addresses
[VCD-CLI] List allocated IP addresses
This CLN contains cli aommnad for listing allocated ip and gateways name
associated with given external_network.It also contains related test
cases.
User can call this cli command as:
vcd network external list-allocated-ip <ext_net_name>
vcd network external list-allocated-ip <ext_net_name> --filter
name==<gateway_name>
Testing done:
Test case for list associated gateways  is added to a test class,
extnet_tests.py

List allocated ip

---

vcd_cli/task.py

With PR 348 on pyvcloud, flufl.enum has been replaced with standard python enum.
As a fallout in vcd-cli, code pieces that were using flufl.enum constructs like _enum had to be replaced with their enum counterparts.
Testing done:
Without the current change all commands fail in vcd-cli
With the change in : 
checked manually that the following commands that are affected by the change succeed
vcd task list -h
vcd task update -h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/300)

Handle fallout of replacing flufl.enum with standard enum in pycloud.

---

system_tests/extnet_tests.py
vcd_cli/network.py

[VCD-CLI] List gateway IP sub-allocation
This CLN contains functionality of listing gateway IP sun allocation
with given external network.
User can call this command as:
vcd network external list-sub-allocated-ip <ext_net_name>
vcd network external list-sub-allocated-ip <ext_net_name> --filter
name==<gateway_name>
Testing done:
Test case for list gateways sun allocated ip   is added to a test class,
extnet_tests.py
To help us process your pull request efficiently, please include:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/302)

VP 1267: [VCD-CLI] List gateway IP sub-allocation

---

system_tests/extnet_tests.py
vcd_cli/network.py

vcd-cli command to list associated direct org vDC networks in external network
Command to list the direct Org vdc networks associated with external network:
vcd network list-direct-org-vdc-network ExtNw
vcd network external list-direct-org-vdc-network ExtNw --filter connectedTo==Ex*
Testing done :
Added test: "test_0075_list_associated_direct_org_vdc_networks"
Status: passed

VP-1246:List associated direct org vDC networks in external network

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

VP-1524: List Rate limits of the gateway
VP-1629: Disable rate limit of the gateway
User would be able to list the rate limits of the gateway using command line : 
vcd gateway configure-rate-limits list test_gateway1
User would be able to disable the rate limits of the gateway using command line: 
vcd gateway configure-rate-limits disable test_gateway1 -e ExtNw
Testing:
Added: test_0019_list_rate_limit and test_0020_disable_rate_limit test case to gateway_test.py and All test cases are passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/304)

VP-1524,VP-1629:List Rate Limits and disable Rate limit

---

system_tests/extnet_tests.py
vcd_cli/network.py

List the vSphere Networks associated with the external networks.
Result will be in below format:
Name            vCenter
-----------      ---------
DPortGroup5   vc1
TestbedPG2     vc2
Command to list the vsphere network:
vcd network external list-vsphere-network ExtNw --filter networkName==ExtNw
Testing done:
Added test case : test_0080_list_vsphere_networks
Test status : passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/305)

VP-1603:List vSphere Networks

---

system_tests/extnet_tests.py
vcd_cli/network.py

Changed vc-name from argument to an option in create command to maintain consistency. Also, renamed "--vc-name" options to "--vc" in attach-port-group and detach-port-group commands.
Also, fixed Flake8 failures.
Testing done:
Ran extnet_tests.py, all tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/308)

Making vc-name an option in external network commands

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

VCDCLI support to add default gateway, enable/disable the dns realy and list the supported configured default gateway.
Implemented configure_default_gateway, configure_dns_default_gateway, list_configure_default_gateways in gateway.py.
VP-1474: Configure default gateway
User would be able to enable the default gateway for provided external network and IP
e.g:
vcd gateway configure-default-gateway update gateway1
-e extNw1 --gateway-ip 2.2.3.1 --default-gateway-enable
VP-1657: Enable/Disable the DNS Relay
User would be able to enable/disable the DNS Relay
e.g:
vcd gateway configure-default-gateway enable-dns-relay gateway1 --dns-relay-enable
VP-1659: List default gateway
User would be able list the configured default gateway
e.g:
vcd gateway configure-default-gateway list gateway1
Testing: …

VP-1474,VP-1657,VP-1659:Configure default gateway,DNS and list

---

system_tests/routed_tests.py
vcd_cli/routed.py

Adding support to list allocated IP Addresses of a org vdc routed network. Listing three columns, 'IP Address', 'Is Deployed' and 'Type'.
Sample command:
vcd network routed list-allocated-ip <routed-network>
Sample output:
IP Address          Is Deployed         Type
=======         ========         =========
20.30.40.1           true                      vsmAllocated
Testing done:
Added a test test_0040_list_allocated_ip_address to routed_test.py. All test cases in the class are passing.

[VP-1376] List IP allocations of a routed org vdc network

---

system_tests/dhcp_pool_test.py
vcd_cli/dhcp_pool.py
vcd_cli/vcd.py

VP-1550: Add DHCP Pool
VCDCLI: User would be able to add DHCP pool to the gateway using command line e.g:
vcd gateway services dhcp-pool create gateway1 --range 30.20.10.11-
30.20.10.15 --enable-auto-dns --gateway-ip 30.20.10.1 --domain
abc.com --primary-server 30.20.10.20 --secondary-server 30.20.10.21
--expire-lease --lease 8640 --subnet 255.255.255.0
Created dhcp_pool.py to achieve  add DHCP Pool
Testing : done
Added dhcp_pool_test.py , and all test cases are passing

VP-1550: Add DHCP Pool

---

system_tests/dhcp_pool_test.py
vcd_cli/dhcp_pool.py

VP-1553: Delete DHCP Pool
User would be able to delete the DHCP pool of the gateway
e.g:
vcd gateway services dhcp-pool delete test_gateway1 pool-1
Output: 
DHCP Pool deleted successfully
Test: Testing done.
Added test_0098_teardown method to dhcp_pool_test.py
All test cases are passing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/316)

VP-1553: Delete DHCP Pool

---

system_tests/routed_tests.py
vcd_cli/routed.py

Added command to list vApps connected to an org vdc routed network.
Command:
vcd network routed list-connected-vapps <routed-network>
Output:
Name                 Status
-------------------  ----------
test-connected-vapp  UNDEPLOYED
Testing done:
Added a test test_0050_list_connected_vapps to routed_tests.py. All test cases in this class are passing.

[VP-1378]: List connected vApps to org vDC routed network

---

system_tests/base_config.yaml
system_tests/gateway_tests.py
system_tests/routed_tests.py
vcd_cli/gateway.py
vcd_cli/network.py
vcd_cli/routed.py

User can add DNS details in routed network usinf CLI command: vcd network routed add-dns vdc_routed_nw --dns1 2.2.3.1 --dns2
2.2.3.2 --dns-suffix domain.com
It also include isolated network creation failure and gateway creation failure
Testing Done: Added new test case in routed_test for add DNS details and executed them successfully
Manually created isolated network successfully
Executed gateway test successfully.
@shashim22 @chaitanya118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/320)

[VP-1683] Add support for adding DNS details in routed network

---

system_tests/routed_tests.py
vcd_cli/routed.py

Added command to remove static IP pool from a routed network.
Command:
vcd vcd network routed remove-ip-range routed-vdc-network -i 30.20.10.2-30.20.10.50
Testing done:
Added a test case test_0016_remove_ip_range to routed_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/321)

[VP-1366]: Remove static IP pool from a routed network under Network Specification

---

vcd_cli/network.py
vcd_cli/routed.py

Help messages were not having correct parameter names.
Testing done:
Ran routed_tests.py, all tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/323)

Correction of network commands help messages

---

system_tests/routed_tests.py
vcd_cli/routed.py

It includes below options:
1: Convert to Subinterface. Command: vcd network routed convert-to-internal-interface vdc_routed_nw
2: Convert to Distributed Routing. Command: vcd network routed convert-to-distributed-interface vdc_routed_nw
3: Routed vdc network Info. Command: vcd network routed info vdc_routed_nw
Testing Done: Added new test cases and executed them successfully.
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/324)

[VP-1386, VP-1388, VP-1532] Provided options for converting to SubInterface, Distributed Routing and network Info

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

Added new command to fetch object types and object for forewall rule edit.
vcd gateway services firewall list-object-types test_gateway1 --type source
vcd gateway services firewall list-objects test_gateway1 --type source--object-type gatewayinterface
@guptaankit52 @kousgy123

[VP 1768]Provided CLi support for list objects and object types for firewall rule edit

---

system_tests/static_route_tests.py
vcd_cli/static_route.py
vcd_cli/vcd.py

Vcd-cli command to "add and list static routes".
Commands to create and list static routes:
vcd gateway services static create test_gateway1 --type User
--network 192.169.1.0/24 --next-hop 2.2.3.30 --mtu 1500
--desc "Static Route Created" -v 0
vcd gateway services static list test_gateway1
Testing done:
test_0000_setup ( Add static route)
test_0025_list_static_routes
Both tests passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/329)

VP-1605,1610: Add and list static routes

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

User can add services in the existing firewall rule.
Command: vcd gateway services firewall update test_gateway1 rule_id
--destination ExtNw:gatewayinterface
--destination ExtNw1:gatewayinterface
--destination vm1:virtualmachine
--source ExtNw:gatewayinterface
--source 10.20.3.2:ip
--service tcp any any
Testing Done: Updated firewall edit command to support service. Executed the complete class successfully.
@shashim22 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/334)

[VP-1735] Adding CLI support for Edit service of firewall rule

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1535:[VCDCLI]: Enable Firewall rule.
Adding a comands to enable/disable firewall rule on the basis of rule id.
To enable a firewall rule, following command can be used:
vcd gateway services firewall enable rule_id gateway_name
To disable a firewall rule, following command can be used:
vcd gateway services firewall disable rule_id gateway_name
Testing Done:
Added test_0041_enabled_firewall_rules,test_0042_disabled_firewall_rules to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/335)

VP-1535:[VCDCLI]: Enable Firewall rule

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1541:[VCDCLI]: Delete a firewall rule.
Adding a comands to delete firewall rule on the basis of rule id.
To delete a firewall rule, following command can be used:
vcd gateway services firewall delete gateway_name rule_id 
Testing Done:
Added test_0051_delete_firewall_rule to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/337)

VP-1541:[VCDCLI] Delete a firewall rule

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

Added a command to create vApp network.
Command:
vdc vapp create-vapp-network vapp1 vapp-network1
--subnet 192.168.1.1/24
--description 'vApp network'
--dns1 8.8.8.8
--dns2 8.8.8.9
--dns-suffix example.com
--ip-range 192.168.1.2-192.168.1.49
--ip-range 192.168.1.100-192.168.1.149
--guest-vlan-allowed-enabled
Testing done:
Added a test case test_0001_create_vapp_network to new test class vapp_tests.py. All test cases are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/336)

[VP-1393]: Create a vApp network.

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1560:[VCDCLI] Get Firewall rule info.
Adding a command to info firewall rule on the basis of rule id.
To info a firewall rule, following command can be used:
vcd gateway services firewall info gateway_name rule_id 
Testing Done:
Added test_0061_info_firewall_rule to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/339)

VP-1560:[VCDCLI] Get Firewall rule info

---

requirements.txt
system_tests/extnet_tests.py

Jenkin's test cases execution were failing complaining "ModuleNotFoundError: No module named 'pyvcloud.vcd.firewall_rule'.
Reason: It pulls the pyvcloud dependency from pypi.org. Since, newer changes were not available in pipy, it was failing complaining "ModuleNotFoundError:". As of now, I pushed the .dev build to pypi and updated the CLI dependencies. At least the initial failure "ModuleNotFoundError:" is fixed.
I have also reverted the PortgroupHelper dependency in environment.py as it was failing complaining system_test module not found.
Testing Done: https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-vcdcli-1.0-STF/30/console
@shashim22

Update the pyvcloud dependency to latest

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1539 : [VCDCLI]: Edit Firewall rule name.
Enhanced the update feature to support edit of firewall rule name as well .
To rename a firewall rule, following command can be used:
vcd gateway services firewall update gateway_name rule_id  --name new_name 
Testing Done:
Enhanced test_0031_update to firewall_rule_tests.py to verify name edit. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/341)

VP-1539 : [VCDCLI]: Edit Firewall rule name

---

system_tests/routed_tests.py
system_tests/run_system_tests.sh
vcd_cli/routed.py

Updated the below command:
vcd network routed add-ip-range routed_net1
--ip-range  2.2.3.1-2.2.3.2
--ip-range 2.2.4.1-2.2.4.2
Add IP range/s to a routed org vdc network
vcd network routed update-ip-range routed_net1
--ip-range 192.168.1.2-192.168.1.20
--new-ip-range 192.168.1.25-192.168.1.50
Update an IP range of a routed org vdc network
It also include the adding of missing test case to run_system_tests.py file.
Testing Done: Executed the routed nw test successfully.
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/344)

 Modified the command to look consistent and added missing test case

---

system_tests/routed_tests.py
vcd_cli/routed.py

vcd network routed delete-ip-range routed_net1
--ip-range 192.168.1.2-192.168.1.20
Delete an IP range from a routed org vdc network
Testing Done: Executed the routed nw test successfully
@shashim22

Updated the command to delete from remove

---

system_tests/extnet_tests.py
vcd_cli/network.py

Some of the help messages aren't correct. Also, renamed some of the commands to have uniform experience across the product.
Testing done:
Ran extnet_test.py, all test cases are passing.

Fix external network command help messages

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1790 : [VCD-CLI] : List Firewall Source.
Adding a command to list firewall rule's source  of rule id.
To list a firewall rule's source, following command can be used:
vcd gateway services firewall source-list gateway_name rule_id 
Testing Done:
Added test_0081_list_firewall_rule_source to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/349)

VP-1790 : [VCD-CLI] : List Firewall Source

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1545 : [VCDCLI] Change the sequence of the firewall rules.
Adding a command to change firewall rule's sequence on the basis of rule id.
To change a firewall rule's sequence , following command can be used:
vcd gateway services firewall update-sequence gateway_name rule_id  --index new_index
Testing Done:
Added test_0091_update_firewall_rule_sequence to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/352)

VP-1545 : [VCDCLI] Change the sequence of the firewall rules

---

vcd_cli/static_route.py

Below command is failing:
vcd gateway services static-route create -h
because -h for --next-hop is matching with -h help.

Remove -h for --next-hop

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1792 : [VCDCLI] delete values from Firewall Source.
Adding a command to delete firewall rule's source value of rule id.
To delete a firewall rule's source value, following command can be used:
vcd gateway services firewall delete-source gateway_name rule_id  source_value
Testing Done:
Added test_0071_delete_firewall_rule_source to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/354)

VP-1792 : [VCDCLI] delete values from Firewall Source

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1841 : [VCD-CLI] : List Firewall Destination.
Adding a command to list firewall rule's destination of rule id.
To list a firewall rule's destination, following command can be used:
vcd gateway services firewall list-destination gateway_name rule_id
Testing Done:
Added test_0082_list_firewall_rule_destination to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/359)

VP-1841 : [VCD-CLI] : List Firewall Destination

---

system_tests/nat_rule_tests.py
vcd_cli/nat_rule.py

Change the NAT rule sequence/order using vcd-cli
New command added:
vcd gateway services nat reorder
Testing done: 
Added test 'test_0045_reorder_nat_rule' and it's passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/362)

VP-1593: Change the NAT rule sequence

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1794 : [VCD-CLI] delete values from Firewall Destination.
Adding a command to delete firewall rule's destination value of rule id.
To delete a firewall rule's destination value, following command can be used:
vcd gateway services firewall delete-destination gateway_name rule_id source_value
Testing Done:
Added test_0072_delete_firewall_rule_destination to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/360)

VP-1794 : [VCD-CLI] delete values from Firewall Destination

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1846 : [VCD-CLI] List Firewall Service.
Adding a command to list firewall rule's services of rule id.
To list a firewall rule's services, following command can be used:
vcd gateway services firewall list-service gateway_name rule_id
Testing Done:
Added test_0083_list_firewall_rule_service to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/364)

VP-1846 : [VCD-CLI] List Firewall Service

---

requirements.txt

It looks like vcd-cli doesn't pick the latest changes from pysdk because of that I am pushed latest changes to pypi and updating the CLI reference.
Testing Done: python setup.py develop refers to latest pysdk
https://pypi.org/project/pyvcloud/20.0.4.dev42/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/365)

Updating the pysdk version to fix jenkin's test failure

---

system_tests/firewall_rule_tests.py
vcd_cli/firewall_rule.py

VP-1796 : [VCD-CLI] delete values from Firewall Service.
Adding a command to delete firewall rule's service of rule id.
To delete a firewall rule's service, following command can be used:
vcd gateway services firewall delete-service gateway_name rule_id protocol
Testing Done:
Added test_0073_delete_firewall_rule_service to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/366)

VP-1796 : [VCD-CLI] delete values from Firewall Service

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

This CL addes rest-vapp-network and delete-vapp-network commmands to vapp.
Added following tests to vapp: test_0020_poweron_vapp, test_0030_reset_vapp_network, test_0040_delete_vapp_network
Testing done:
manually run the commands.
ran the complete vapp tests locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/363)

VP-1396, VP-1398: reset and delete vapp network commands.

---

system_tests/gateway_tests.py
vcd_cli/gateway.py

VP-1862 : [Vcd-Cli] Added code to set syslog server IP for gateway.
Adding a command to set syslog server IP of a gateway.
To set a syslog server IP, following command can be used:
vcd gateway set-syslog-server  gateway_name ip_address
Testing Done:
Added test_0031_set_tenant_syslog_ip to gateway_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/368)

VP-1862 : [Vcd-Cli] Added code to set syslog server IP for gateway

---

system_tests/vm_tests.py
vcd_cli/vm.py

This CL adds add-nic and list-nics commands to the vm command.
Added vm_tests to cover these two commands.
Testing done: ran the commands manually.
ran the newly added tests successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/371)

VP-1797, VP-1800: add-nic and list-nics commands to vm.

---

system_tests/vm_tests.py
vcd_cli/vm.py

this CL adds delete-nic command to the vm command group.
added test case for the same in vm_tests
testing done: ran the command locally.
ran the test cases in dev setup successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/372)

VP-1802: vm: delete-nic command

---

system_tests/vapp_tests.py
vcd_cli/vapp.py
vcd_cli/vapp_network.py
vcd_cli/vcd.py

New commands have been provided to add IP range and delete them.
Commands:
vdc vapp network add-ip-range vapp1 vapp-network1
--ip-range 6.6.5.2-6.6.5.20
Add IP range to the vApp network.
vdc vapp network delete-ip-range vapp1 vapp-network1
--ip-range 6.6.5.2-6.6.5.20
Delete IP range of the vApp network.
Testing Done: Test case has been added and executed them successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/378)

Added support for add IP range and delete

---

system_tests/gateway_tests.py

Jenkins CToT is failing complaining "multiple gateway with same name exists"
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-vcdcli-1.0-STF/102/
Testing Done: Executed the gateway_tests successfully

Appending UUID to gateway2 for update gateway name test case

---

system_tests/vapp_tests.py
vcd_cli/vapp_network.py

VP-1902 : [VCDCLI] Update vApp network.
To update a vapp network, following command can be used:
vcd vapp network update  vapp_name vapp_network_name -n vapp_network_new_name -d vapp_network_new_description
Testing Done:
Added test_0031_update_vapp_network to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/380)

VP-1902 : [VCDCLI] Update vApp network

---

system_tests/vapp_tests.py
vcd_cli/vapp_network.py

VP-1926 : [VCDCLI] Update IP range of vApp network.
VP-1930 : [VCDCLI] Add DNS details to vApp network.
Adding a commands to Update IP range and Add DNS details to vApp network.
To Update IP range of a vApp network, following command can be used:
vdc vapp network update-ip-range vapp1 vapp-network1 --ip-range 6.6.5.2-6.6.5.20 --new-ip-range 6.6.5.10-6.6.5.18 
To Add DNS details of a vApp network, following command can be used:
vdc vapp network add-dns vapp1 vapp-network1 --dns1 6.6.5.2 --dns2 6.6.5.10-6.6.5.18 --dns-suffix example.com
Testing Done:
Added test_0036_update_ip_range_to_vapp_network , test_0038_add_dns_to_vapp_network to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

VP-1926, VP-1930

---

system_tests/vapp_network_dhcp_tests.py
vcd_cli/vapp_network.py
vcd_cli/vapp_network_dhcp.py
vcd_cli/vcd.py

VP-1938 : [VCDCLI] Enable DHCP of vApp network.
VP-1940 : [VCDCLI] Disable DHCP of vApp network.
Adding a commands to enable DHCP service of vapp network.
To enable DHCP service following command can use:
vcd vapp network services dhcp enable-dhcp  vapp_name network_name --enable.
To disable DHCP service following command can use:
vcd vapp network services dhcp enable-dhcp  vapp_name network_name --disable.
Adding a commands to set DHCP service of vapp network.
To set DHCP service following command can use:
vcd vapp network services dhcp set vapp_name network_name --i 10.11.11.1-10.11.11.100
--default-lease-time 4500  --max-lease-time 7000
Testing Done:
Added test_0011_set_dhcp_service,test_0012_enable_dhcp_service to vapp_network_dhcp_tests.py. 
All test cases in this class are passing. …

VP-1938, VP-1940

---

system_tests/vapp_network_firewall_tests.py
vcd_cli/vapp_network_firewall.py
vcd_cli/vcd.py

VP-1942: [VCDCLI] Enable Firewall of vApp network.
VP-1944: [VCDCLI] Disable Firewall of vApp network.
Adding a commands to enable/disable firewall service of vapp network.
To enable firewall service following command can use:
vcd vapp network services firewall enable-firewall vapp_name network_name --enable.
To disable firewall service following command can use:
vcd vapp network services firewall enable-firewall vapp_name network_name --disable.
Testing Done:
Added test_0011_enable_firewall_service to vapp_network_firewall_tests.py.
All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/387)

VP-1942, VP-1944

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2085 : [VcdCLI]Stop vApp.
Adding a command to stop a vApp.
To stop  a vApp, following command can be used:
vcd vapp stop vapp_name
Testing Done:
Added test_0025_stop_vapp to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/396)

VP-2085 : [VcdCLI]Stop vApp

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2087:[VcdCLI]Discard suspended state.
VP-2091:[VcdCLI] Enter maintenance mode.
VP-2093:VcdCLI] Exit maintenance mode.
VP-2199:[VcdCLI]suspend vapp.
Adding  commands to suspend , discard suspended state,  enter maintenance mode, exit maintenance mode a vapp.
To suspend a vapp, following command can be used:
vcd vapp suspend vapp_name
To discard suspended state of vapp, following command can be used:
vcd vapp exit-maintenance-mode vapp_name
To enter maintenance mode a vapp, following command can be used:
vcd vapp enter-maintenance-mode vapp_name
To exit maintenance mode a vapp, following command can be used:
vcd vapp exit-maintenance-mode vapp_name
Testing Done:
Added test_0026_suspend_vapp,  test_0027_discard_suspended_state_vapp, test_0028_enter_maintenance_mode, …

VP-2087,VP-2091,VP-2093,VP-2199

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2099 : [VcdCLI] Download vapp.
Adding a command to download a vapp.
To download a vapp, following command can be used:
vcd vapp download vapp_name
Testing Done:
Added test_0060_download_ova to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/401)

VP-2099 : [VcdCLI] Download vapp

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2095 : [VcdCLI] Upgrade Virtual Hardware version a vapp
Adding a command to upgrade virtual hardware of vapp.
To  to upgrade virtual hardware , following command can be used:
vcd vapp  upgrade-virtual-hardware vapp_name
Testing Done:
Added test_0070_upgrade_virtual_hardware to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/402)

VP-2095 : [VcdCLI] Upgrade Virtual Hardware version a vapp

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

**Added filter for " vcd vapp list" command**
With this change we have added filter in list_vapps() method as with exiting method the "vcd vapp list" only having option to provide vapp name as argument but the command having no filter to get list of vApp based on vApp ownerName, numberOfVMs, status etc., 
**Testing Done :** 
-------------------------------------------------------------
Tested the filter with below options : 
vcd login cassini.eng.vmware.com system administrator -i -w
vcd org use Development
vcd vapp list
vcd vapp list --filter ownerName==pgorlewar:
vcd vapp list --filter numberOfVMs==7
vcd vapp list --filter name==Testbed-Pooja
vcd vapp list --filter vdcName==DevelopmentOrgVdc
vcd vapp list --filter status==POWERED_ON
--- …

Added filter for 'vcd vapp list' command

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2062: Reboot the VM
This CLN contains functionality of reboot VM and corresponding test
case. It can be called as :
vcd vm reboot vapp1 vm1
Testing Done: Test class vapp_tests.py contains test method
test_0032_reboot and it executes successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/409)

VP-2062: Reboot the VM

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2061 : [VcDCLI] shutdown VM
This CLN contains shutdown VM functionality and corresponding test case.
vcd vm shutdown vapp1 vm1
Testing Done:
Test method test_0034_shutdown() is added in class vm_tests.py and it is
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/410)

VP-2061 : [VcDCLI] shutdown VM

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2053: [VcDCLI] create snapshots.
This CLN contains VM functionality to create snapshot of a VM. It also
has reltaed test case in file vm_tests.py.
vcd vm create-snapshot vapp1 vm1
Testing Done: Test case test_0140_create_snapshot is added in
vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/412)

VP-2053: [VcDCLI] create snapshots

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2055: [VcDCLI] remove snapshots to current
This CLN contains functionality to revert snapshots to current and it's
test case is added in test class vm_tests.py.
vcd vm revert-to-snapshot vapp1 vm1
Testing Done:
Test method test_0150_revert_to_snapshot is added in vm_tests.py which
is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/413)

VP-2055: [VcDCLI] remove snapshots to current

---

system_tests/vm_tests.py
vcd_cli/vm.py

[Vcd-CLI]Copy To VM from one vapp to another
This CLN contains functionality and test case for copying VM from one
vapp to another. It can be involked in vcd-cli as:
vcd vm copy vapp1 vm1 vapp2 vm2
Testing Done: Test method test_0025_copy_to() is added to vm_tests.py
class. It is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/414)

VP-2036: [Vcd-CLI]Copy to VM from one vapp to another

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2040: [Vcd-CLI] Delete VM
This CLN has delete VM functionality and corresponding test case
test_0028_delete. From cli, it can be called as :
vcd vm delete vapp1 vm1
Testing Done:
test_0028_delete method is added for testing delete VM and it is
executed successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/415)

VP-2040: [Vcd-CLI] Delete VM

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2101 : [VcdCLI] Copy to vapp.
This CLN contains copy to  vapp functionality and corresponding test case.
vcd vapp copy-to vapp1 -n new_vapp_name -v target_vdc_name -d description
Testing Done:
Test method test_0080_copy_to() is added in class vapp_tests.py and it is
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/411)

VP-2101 : [VcdCLI] Copy to vapp

---

requirements.txt

VP-2395 : Fix - click version issue of VCD-CLI.
This CLN contains changes according to 
vcd-cli 21.1.0 have issue.
If this will run on click version of 6.7 or less then it will not work.
It will work perfectly with click version 7.0 because
code changes in https://jira.eng.vmware.com/browse/VP-2153 contain hidden attribute of click that was added in 7.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/416)

VP-2395 : Fix - click version issue of VCD-CLI

---

system_tests/run_system_tests.sh

VP-2410: [VCD-CLI] Feature to add test files automatically.
This feature will enable developer not to add their new test files into
run_system_tests.sh manually. New test files will be picked
automatically. There is a provision for unstable tests which can be
enabled for particular test files manually.
Testing Done:
CI/CD will test the script in next run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/420)

VP-2410: [VCD-CLI] Feature to add test files automatically.

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2038: [Vcd-CLI] Move To VM from one VAPP to another vapp.
This CLN contains functionality to move VM from one vapp to another. It
can be called as :
vcd vm move vapp1 vm1 vapp2 vm2
Testing Done:
Test case test_0026_move_to is added in vm_tests.py and it is executing
successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/423)

VP-2038: [Vcd-CLI] Move To VM from one VAPP to another vapp.

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2107 : [VcdCLI] create snapshot vapp.
This CLN contains create snapshot of a vapp functionality and corresponding test case.  
vcd vapp create-snapshot vapp1  --is-include-memory True --quiesce True
Test method test_0100_create_snapshot() is added in class vapp_tests.py and it is  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/422)

VP-2107 : [VcdCLI] create snapshot vapp

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2109 : [VcdCLI] Revert to snapshot of vapp
VP-2111 : [VcdCLI] Remove the snapshot of vapp
This CLN contains revert to snapshot and  remove all the snapshot of a vapp functionality and corresponding test case.  
vcd vapp revert-to-snapshot vapp1
vcd vapp remove-all-snapshot vapp1 
Test methods test_0110_revert_to_snapshot() and test_0120_snapshot_remove_all is added in class vapp_tests.py and it is  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/424)

VP-2109 and VP-2111

---

system_tests/vm_tests.py
vcd_cli/vm.py

[VcdCli] Attach Disk
THis CLN contains functionality to attach independent disk to VM. It can
be called as:
vcd vm attach-disk vapp1 vm1 --idisk-href <idisk-href>
Testing Done:
One test method test_0160)attach_disk_to_vm is added in vm_tests.py file
and it executes successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/428)

VP-2048: [VcdCli] Attach Disk

---

system_tests/vapp_tests.py
vcd_cli/vapp_network.py

VP-2113 : [VcdCLI] List vApp Networks.
This CLN contains list all vapp networks functionality and corresponding test case.  
It can be called as  
vcd vapp network list vapp1  
Test methods test_0044_list_vapp_networks is added in class vapp_tests.py and it is  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/429)

VP-2113 : [VcdCLI] List vApp Networks

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2032: [Vcd-CLI]Upgrade Virtual Hardware version
VP-2056: [VcDCLI] deploy VM
VP-2057: [VcDCLI] undeploy VM
This CLN contains deploy, undeploy and upgrade virtual hardware version of vm functionality and corresponding test case.
vcd vm deploy vapp1 vm1
vcd vm undeploy vapp1 vm1
vcd vm upgrade-virtual-hardware vapp1 vm1
Testing Done:
Test methods test_0170_deploy_undeploy_vm and test_0180_upgrade_virtual_hardware is added in class vm_tests.py and it is
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/432)

VP-2032, VP-2056, VP-2057

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2064: [VcdCLI]List selected VM general properties.
This CLN contains a command for show general setting of vm functionality and corresponding test case.
vcd vm general-setting vapp1 vm1
Testing Done:
Test methods test_0190_general_setting_detail is added in class vm_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/433)

VP-2064: [VcdCLI]List selected VM general properties

---

system_tests/vapp_tests.py
vcd_cli/vapp_network.py

VP-1412 : [vcdcli] Edit DNS Under Network Specification.
This CLN contains a command for update DNS detail of vapp network functionality and corresponding test case.
vdc vapp network update-dns vapp1 vapp-network1 --dns1 6.6.5.2 --dns2 6.6.5.10-6.6.5.18  --dns-suffix example.com
Testing Done:
Test methods test_0040_update_dns_of_vapp_network is added in class vapp_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/438)

VP-1412 : [vcdcli] Edit DNS Under Network Specification

---

system_tests/vapp_tests.py
vcd_cli/vapp_network.py

VP-2594 : [vcdcli] Show DNS detail of Vapp Network.
This CLN contains a command for DNS details of vapp network functionality and corresponding test case.
vdc vapp network dns-info vapp1 vapp-network1
Testing Done:
Test methods test_0041_dns_info is added in class vapp_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/440)

VP-2594 : [vcdcli] Show DNS detail of Vapp Network

---

system_tests/vm_tests.py
vcd_cli/vm.py

[VcdCLI] Detach Disk
THis CLN contains functionality to detach independent disk from VM. It
can be called as:
vcd vm detach-disk vapp1 vm1 --idisk-href <idisk-href>
Testing Done:
One test method test_0170_detach_disk_from_vm is added in vm_tests.py
file and it executes successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/441)

VP-2050: [VcdCLI] Detach Disk

---

system_tests/vm_tests.py
vcd_cli/vm.py

[VcdCLI] Reload from VC
This CLN contains VM functionality to reload from VC. It can be called
from command line as:
vcd vm reload-from-vc vapp1 vm1
Testing Done: Test method test_0220_reload_from_vc is added in
vm_tests.py file and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/442)

VP-2072: [VcdCLI] Reload from VC

---

system_tests/vapp_tests.py
vcd_cli/vapp_network.py

VP-1400: [VcdCli] Synchronize syslog server settings
VP-2599 : [VcdCli] Make connection of vapp network
This CLN contains a command for Make connection of vapp network and Synchronize syslog server settings of vapp network functionality and corresponding test case.
vcd vapp network connect-ovdc vapp1 vapp-network1 ovdc_network_name
vcd vapp network sync-syslog-settings vapp1 vapp-network1
Testing Done:
Test methods test_0012_connect_vapp_network_to_ovdc_network() and test_0013_sync_syslog_settings are added in class vapp_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/445)

VP-1400, VP-2599

---

system_tests/vm_tests.py
vcd_cli/vm.py

[VcdCLI] CUstomize at Next Power ON
This CLN contains VM functionality customize at next power on. It can be
called from command line as :
vcd vm customize-on-next-poweron vapp1 vm1
Testing Done:
Test case is not included because corresponding API returns 204 no
content.Manual testing done. In VCD host, guest customization logs
tested manually while powering on the VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/444)

VP-2080: [VcdCLI] CUstomize at Next Power ON

---

system_tests/vapp_tests.py
vcd_cli/vapp.py
vcd_cli/vapp_network.py

VP-1909: [VCDCLI] Create vApp network using OrgvDC Network
VP-1922: [VCDCLI] Enable Fence vApp
VP-2621: [VcdCli] Enable disable download in vapp
This CLN contains a command for Create vApp network using OrgvDC Network, Enable Fence vApp and Enable disable download of vapp functionality and corresponding test case.
vcd vapp enable-download vapp1
vcd vapp disable-download vapp1
vdc vapp network create-ovdc-network vapp1 ovdc-network1
vdc vapp network enable-fence vapp1
Testing Done:
Test methods test_0130_create_vapp_network_from_ovdc_network(), test_0131_enable_fence_mode(),  test_0140_enable_download() and test_0150_disable_download() are added in class vapp_tests.py and it is executing successfully.
--- …

VP-1909, VP-1922, VP-2621

---

system_tests/vapp_tests.py
vcd_cli/vapp.py
vcd_cli/vapp_network.py

VP-2629: [VcdCli]show Lease setting in vapp
VP-2623: [VcdCli]show metadeta in vapp
This CLN contains a command for show Lease setting and show metadeta of vapp functionality and corresponding test case.
vcd vapp show-lease vapp1
vcd vapp show-metadata vapp1
Testing Done:
Test methods test_0160_show_lease() and test_0170_show_metadata() are added in class vapp_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/449)

VP-2629, VP-2623

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2631: [VcdCli]Start time action in vapp
VP-2632: [VcdCli]Stop time action in vapp
This CLN contains a command for update startup section of vapp for given vm and corresponding test case.
vcd vapp update-startup-section vapp1 vm1  --o 2 --start-action powerOn
--start-delay 2 --stop-action powerOff -stop-delay 4
Testing Done:
Test methods test_0180_update_startup_section() is added in class vapp_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/451)

VP-2631, VP-2632

---

system_tests/base_config.yaml
system_tests/vm_tests.py
vcd_cli/vm.py

VP-2022:[Vcd-CLI]Power on with force Recustomization for a VM
VP-2677:[VCD-CLI] Get GuestCustomizationSectionStatus
VP-2690:[VCD-CLI] Enable GC
This CLN contains above three functionalitie and it can be called from
command line as:
vcd vm gc-enable vapp1 vm1 --enable
vcd vm gc-status vapp1 vm1
vcd vm poweron-force-recustomize vapp1 vm1
Testing Done:
Corresponding test cases are added in vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/450)

VP-2022,VP-2677,VP-2690: [Vcd-CLI]Power on with force Recustomization for a VM

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2649: [VCD-CLI] GET virtualHardwareSection-disks
VP-2660: [VCD-CLI] get virtualHardwareSection/media
VP-2663: [VCD-CLI] Get virtualHardwareSection/networkCards
This CLN contains above functionalities and it can be called with
default options from command line as :
vcd vm list-virtual-hardware-section vapp1 vm1
Testing Done:
Test method test_0280_list_virtual_hardware_section is added in
vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/452)

VP-2649, VP-2660, VP-2663: List virtual hardware section

---

system_tests/vapp_tests.py
vcd_cli/vapp.py

VP-2626: [VcdCli]show product section in vapp,
VP-2721: [VcdCli]show startup section of vapp,
VP-2726: [VcdCli]update product section in vapp,
This CLN contains a command for show startup section, show product section and  update product section of vapp and corresponding test case.  
It can be called as  
vcd vapp show-startup-section vapp1
vcd vapp show-product-section vapp1
vcd vapp update-product-section vapp1 --key testkey --value testvalue --class_name testclassname 
--instance_name testinstancename --label labledata --is_password true --user_configurable false
Test methods test_0190_show_startup_section(), test_0200_update_startup_section() and test_0210_show_product_section() are added in class vapp_tests.py and it is executing successfully.
--- …

VP-2626, VP-2721, VP-2726

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2625: [VCD-CLI] get compliance result
This CLN contains check compliance functionality of a VM. It can be
called from command line as :
vcd vm get-compliance-result vapp1 vm1
Testing Done:
Test method test_0290_get_compliance_result ia sdded in vm_tests.py
file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/453)

VP-2625: [VCD-CLI] get compliance result

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2636:[VCD-CLI] Get current metrics
VP-2729:[VCD-CLI] List subset of current metrics
VP-2731:[VCD-CLI] List historic metrics
This CLN contains listing VM Metrics. It can be called from command line
as :
vcd vm list-current-metrics vapp1 vm1
vcd vm list_subset_currennt_metrics vapp1 vm1
--metric-pattern *.average
vcd vm list-historic-metrics vapp1 vm1
Testing Done:
Test method test_0300_list_current_metrics and
test_0310_list_subset_current_metrics are added for current metrics.
Historic metrics need VM monitoring set-up which is not in our test lab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/455)

VP-2636, VP-2729, VP-2731: List VM Metrics

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2066: [VcdCLI]Update selected VM general properties
This CLN contains a command for update general setting for given vm and corresponding test case.  
It can be called as  
vcd vm update-general-setting vapp1 vm1 --name vm_new_name --d vm_new_description 
--cn new_computer_name --bd 60  --ebs True
Test methods test_0180_update_startup_section() is added in class vapp_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/457)

VP-2066: [VcdCLI]Update selected VM general properties

---

vcd_cli/vm.py

VP-2763: [VCD-CLI] Get sample historic data of a metric
This CLN contains functionality of listing sample historic data for a
given metric. It can be called from command line as :
vcd vm list-sample-historic-data vapp1 vm1
--metric-name disk.read.average
Testig Done:
This case can not be automated as it requires VM Monitoring set-up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/456)

VP-2763: [VCD-CLI] Get sample historic data of a metric

---

system_tests/datastore_tests.py
system_tests/vm_tests.py
vcd_cli/datastore.py
vcd_cli/vcd.py
vcd_cli/vm.py

VP-2052: [VcDCLI] relocate
VP-2076: [VCD-CLI] List datastores in VCD
Fix for teardown failure.
THis CLN contains above cli commands and fix. These commands can be
called from the command line as :
vcd vm relocate vapp1 vm1 --datastore-id
0d8c7358-3e8d-4862-9364-68155069d252
vcd datastore list
Testing Done:
Test method test_0330_relocate in vm_tests.py and test10_list_datastores
in datastore_tests.py are added.

VP-2052,VP-2076: [VcDCLI] relocate

---

system_tests/vapp_network_firewall_tests.py
vcd_cli/vapp_network_firewall.py

VP-2653:[VcdCli] Add firewall rule in vapp network,
VP-2654:[VcdCli] delete firewall rule in vapp network, 
VP-2739:[VcdCli] update firewall rule default action and log  in vapp network,
VP-2741:[VcdCli] update firewall rule in vapp network, 
VP-2777:[VcdCli] list firewall rule in vapp network
This CLN contains a commands for add, delete,  update default action and log, list
and  update firewall rule in vapp networks,  and corresponding test case.
vcd vapp network services firewall set-default-action vapp_name network_name --action allow --log-action False
vcd vapp network services firewall list vapp_name network_name
vcd vapp network services firewall delete vapp_name network_name --name firewall_rule_name
vcd vapp network services firewall add vapp_name network_name …

VP-2653, VP-2654, VP-2739, VP-2741, VP-2777

---

system_tests/vdc_tests.py
system_tests/vm_tests.py
vcd_cli/vdc.py
vcd_cli/vm.py

VP-2791:[VcdCLI]UPdate nic
VP-2707:[VcdCLI]List media file in VDC
VP-2709:[VcdCLI]Remove href from insert-cd and eject-cd command
Above functionalities are part of the CLN. It can be called from command
line as :
vcd vm update-nic vapp1 vm1
--adapter-type VMXNET3
--primary
--connect
--network network_name
--ip-address-mode MANUAL
--ip-address 192.168.1.10
vcd vdc list-media
Testing Done:
Test method test_0010_list_media in vdc_tests.py and
test_0115_update_nic in vm_tests.py is added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/460)

VP-2791,VP-2709,VP-2707 Update nic

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2673: [VCD-CLI] Update OperatingSystemSection
VP-2796: [VCD-CLI] List Operating system section
This CLN conatins list and update operating system section. It can be
called from command line as :
vcd vm list-os-section vapp1 vm1
vcd vm update-os-section vapp1 vm1
--ovf-info newInfo
--description newDescription
Testing Done:
Test method test_0340_list_os_section and test_0340_update_os_section
added in vm_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/462)

VP-2673, VP-2796: List and update VM Operating system section

---

system_tests/vapp_network_nat_tests.py
vcd_cli/vapp_network_nat.py
vcd_cli/vcd.py

VP-2749: [VcdCli] Enable NAT rule in vapp network
VP-2752: [VcdCli] Select NAT rule type in vapp network
This CLN contains a commands for Enable NAT rule, Select NAT rule type in vapp network and corresponding test case.
vcd vapp network services nat enable-nat vapp_name network_name --enable
vcd vapp network services nat set-nat-type vapp_name network_name --type ipTranslation
--policy allowTrafficIn
Testing Done:
Test methods test_0010_enable_nat_service() and test_0020_update_nat_type() are added in
class vapp_network_nat_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/463)

VP-2749, VP-2752

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2801:[VCD-CLI] List Guest customization section
VP-2675:[VCD-CLI] Update GuestCustomizationSection
VP-2679:[VCD-CLI] CheckPostCustomizationScript
This CLN contains list, update and check postgc script status for guest
customization section. It can be called from command line as:
vcd vm list-gc-section vapp1 vm1
vcd vm update-gc-section --disable
vcd vm check-post-gc-script vapp1 vm1
Testing Done:
Test methods test_0350_list_gc_section,test_0360_update_gc_section and
test_0370_check_post_gc_script_status are added in vm_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/464)

VP-2801,VP-2675,VP-2679 List, update and check postgc script status

---

system_tests/vapp_network_nat_tests.py
vcd_cli/vapp_network_nat.py
vcd_cli/vcd.py

VP-2743: [VcdCli] Add NAT rule in vapp network
VP-2798: [VcdCli] List NAT rule in vapp network
VP-2809: [VcdCli] get NAT type and policy in vapp network
VP-2747: [VcdCli] Delete NAT rule in vapp network
This CLN contains a commands for Add NAT rule, List NAT rule, get NAT type and policy and Delete NAT rule in vapp network and corresponding test case.
vcd vapp network services nat get-nat-type vapp_name network_name
vcd vapp network services nat list vapp_name network_name
vcd vapp network services nat delete vapp_name network_name rule_id
vcd vapp network services nat add vapp_name network_name --type ipTranslation 
--vm_id testvm1 --nic_id 1
Testing Done:
Test methods test_0030_get_nat_type(), test_0040_add_nat_rule(),  test_0050_get_list_of_nat_rule() and …

VP-2743, VP-2798, VP-2809, VP-2747

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2681:[VCD-CLI] Get VmCapabilities
VP-2683:[VCD-CLI] Update VmCapabilities
This CLN contains list and update VM capabilities. It can be called from
command line as :
vcd vm list-vm-capabilities vapp1 vm1
vcd vm update-vm-capabilities
--enable-memory-hot-add
Testing Done:
Test methods test_0380_list_vm_capabilities and
test_0390_update_vm_capabilities are added in vm_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/466)

VP-2681,VP-2683: List and update VM capabilities

---

system_tests/vapp_network_nat_tests.py
vcd_cli/vapp_network_nat.py
vcd_cli/vcd.py

VP-2745: [VcdCli] Update NAT rule in vapp network
This CLN contains a commands for update NAT rule in vapp network and corresponding test case.
vcd vapp network services nat update vapp_name network_name rule_id --vm_id testvm1 --nic_id 1
vcd vapp network services nat update vapp_name network_name rule_id --vm_id testvm1 --nic_id 1 
--mapping_mode manual --ext_ip 10.1.1.1
vcd vapp network services nat update vapp_name network_name rule_id --vm_id testvm1 --nic_id 1 
--ext_port -1 --int_port -1 --protocol TCP_UDP
Testing Done:
Test method test_0060_update_nat_rule() is added in
class vapp_network_nat_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

VP-2745: [VcdCli] Update NAT rule in vapp network

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2685:[VCD-CLI] List RunTime Info section
VP-2687:[VCD-CLI] List BootOptions
VP-2815:[VCD-CLI] Update boot options
This CLN contains runtime info and boot optons list and update features.
Testing Done:
Test methods test_0400_list_runtime_info, test_0410_list_boot_options
and test_0420_update_boot_options are added in vm_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/470)

VP-2685,VP-2687,VP-2815: Runtime info and boot options in VM

---

system_tests/vapp_tests.py

VCD-CLI CI/CD Tests Failure.
Fix vapp move test failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/476)

VCD-CLI Tests Failure

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2622:[VCD-CLI] list metadata
VP-2849:[VCD-CLI] Update metadat
VP-2851:[VCD-CLI] Remove metadata
VP-2856:[VCD-CLI] get metadata
This CLN contains VM metadata CRUD operations.
Testing Done:
test methods test_0430_set_metadata, test_0440_update_metadata,
test_0450_list_metadata and test_0460_remove_metadata added in
vm_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/479)

VP-2622, VP-2849, VP-2851,VP-2856: metadata CRUD operations

---

system_tests/vapp_network_static_route_tests.py
vcd_cli/vapp_network_static_route.py
vcd_cli/vcd.py

VP-2754: [VcdCli] Enable static routing in vapp network
VP-2756: [VcdCli] Add static route in vapp network
VP-2758: [VcdCli] Update static route in vapp network
VP-2760: [VcdCli] Delete static route in vapp network
VP-2811: [VcdCli] List static route in vapp network
This CLN contains a commands for Enable, Add, Update, Delete, List static route in vapp network and corresponding test case.
vcd vapp network services static-route enable-service vapp_name   network_name --enable
vcd vapp network services static-route enable-service vapp_name   network_name --disable
vcd vapp network services static-route add vapp_name network_name route_name network_cidr 
next_hop_ip
vcd vapp network services static-route list vapp_name network_name 
vcd vapp network services static-route …

VP-2754, VP-2756, VP-2758, VP-2760, VP-2811

---

system_tests/vm_tests.py
vcd_cli/vm.py

VP-2657:[VCD-CLI] Update virtualHardwareSection-disks
VP-2664:[VCD-CLI] update virtualHardwareSection/media
This CLN contains virtual hardware section update operation for disk and
media. It can be called from command line as:
vcd vm update-vhs-disk vapp1 vm1
--e-name 'Hard Disk 1'
--v-quantity 694487
vcd vm update-vhs-media  vapp1 vm1
--e-name 'CD DVD DRive'
--host-resource pb1.iso
Testing Done:
Test method test_0500_update_vhs_disk is added. Test method for update
media is not added as it gives response as 405/METHOD_NOT_ALLOWED.

VP-2657,VP-2664: Update virtual hardware section disk and media

---

system_tests/vm_tests.py

Some times suspend VM test case puts VM in partially suspended state and
all other VM operaions gets failed after that. Commenting suspend and
discard suspend state of VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/492)

Comment suspend VM test case.

---

system_tests/vm_tests.py
vcd_cli/vm.py

[VCD-CLI] Remove snapshot of VM.
This can be called from comand line as :
vcd vm remove-snapshot vapp1 vm1
Testing Done:
Test method test_0155_remove_snapshot is added in vm_tests.py.

[VCD-CLI] Remove snapshot of VM.

---

requirements.txt
vcd_cli/login.py
vcd_cli/profiles.py
vcd_cli/task.py
vcd_cli/utils.py

In response to https://github.com/vmware/pyvcloud/pull/637, made the necessary changes in vcd-cli so that vcd-cli can leverage the JWT token for authentication and session restoration.
This changes made in this PR are as follows
* Added a new field in profile to distinguish between x-vcloud-authorization and jwt token
* Addressed removal of rehydrate methods from pyvcloud's client.py
* Adjusted code to accomodate the new streamlined api version negotiation code in pyvcloud.
* Got rid of well known endpoints from profiles, it was not being used anywhere.
* Minor flake8 changes
Testing done:
Manually invoke vcd login command with different api versions, and looked at the logs and profile.yaml to make sure that the correct end points are being used and the right token is being saved. Also …

[VCDA - 1341] Added JWT based authorization support in vcd-cli

---

vcd_cli/vdc.py

Adds --network-quota integer option to the `vcd vdc create`
command, which sets the network_quota setting in the
underlying call to org.create_org_vdc - this is the Maximum
number of network objects that can be deployed in this vdc.
The default value is zero (like the underlying call), which
(unike all the similar settings) means that *no* network
objects can be created within the vdc.
Signed-off-by: Nigel Metheringham <nigel.metheringham@redcentricplc.com>
- (Required) Short description of changes in the PR topic line
- (Required) Detailed description of changes include tests and
documentation.  If the pull request contains multiple commits with 
detailed messages, refer to those instead
- (Optional) Names of reviewers …

Add --network-quota to vdc create

---

AUTHORS
ChangeLog
requirements.txt

[Bug-2423198]: [OSS] - CSE/VCD-CLI fixed pycryptodome version is vulnerable to integer overflow when version < 3.6.6
Updating Changelog and AUTHORS too.
@rajeshk2013

Updating pycryptodome to 3.6.6

---

requirements.txt
vcd_cli/utils.py

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>
* Updated keyring requirement
* This makes vcd-cli comply with python3.10
Testing done
* vcd login
* vcd cse commands
* vcd logout
* vcd cse ovdc list
* vcd role list-rights clusteradmin -o cseorg
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/566)

Update keyring to fix collections.abc alias to support python3.10

---

requirements.txt

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>
Issue: 
`vcd login` command throws the following error -
```
Traceback (most recent call last):
File "/root/v10/bin/vcd", line 5, in <module>
from vcd_cli.vcd import vcd
File "/root/v10/lib/python3.10/site-packages/vcd_cli/vcd.py", line 121, in <module>
from vcd_cli import login  # NOQA
File "/root/v10/lib/python3.10/site-packages/vcd_cli/login.py", line 24, in <module>
from vcd_cli import browsercookie
File "/root/v10/lib/python3.10/site-packages/vcd_cli/browsercookie/__init__.py", line 22, in <module>
from Crypto.Cipher import AES
File "/root/v10/lib/python3.10/site-packages/Crypto/Cipher/__init__.py", line 31, in <module>
from Crypto.Cipher._mode_ctr import _create_ctr_cipher
File …
```

Update pycryptodome to 3.7.0
