vmware/vcd-cli

setup.py, vca_cli/vca_cli.py
- Added dateutils as a requirement for setup
- Changed the date conversion to utilize dateutil.parser instead to
resolve issue #12 https://github.com/vmware/vca-cli/issues/12
=> Use dateutil.parser to resolve issue #12

vca_cli/vca_cli.py
Basic support for score service events in vca_cli.
It's depend on https://github.com/vmware/pyvcloud/pull/53
=> SCOR-13 Add Events support to vca-cli

vca_cli/vca_cli.py
Add "cancel execution" in dep command.
Also style fixes.
=> SCOR-56 Implement cancel workflow execution on score, pyvcloud and vсa-cli

requirements.txt, setup.py, vca_cli/print_utils.py, vca_cli/vca_cli_impl.py
- multiple improvements for:
- blueprints operations:
- new options: --include-plan
(includes blueprint plan on demand)
- deployment operations
- events operations
=> Improve user experience for Score users

.gitignore, .travis.yml, vca_cli/vca_cli_blueprint.py
NOTE: depends on latest changes to pyvcloud
=> Improve Score user experience

vca_cli/vca_cli_blueprint.py
Depends-On: https://github.com/vmware/pyvcloud/pull/77
=> Improve Score CLI usage implementation

requirements.txt
Hello,  I had to add these modules in order to use vca-cli.  Thanks!
=> Adding missing module

vca_cli/cmd_proc.py, vca_cli/vca_cli.py, vca_cli/vca_cli_compute.py
Currently two options are using -v, --version and --vdc
=> Use -V for server version in login command

vcd_cli/vapp.py
=> Adding new optional parameter to vapp create command to provide disk size of the home disk of the first vm.

ChangeLog, vcd_cli/info.py, vcd_cli/role.py, vcd_cli/user.py, vcd_cli/vapp.py
options to customize hostname, vm_name and EULA acceptance
=> vapp create command

vcd_cli/org.py
VCDA-171(vcd-cli) - Create a new organization with just the mandatory user inputs
=>  VCDA-171(vcd-cli) - Create a new organization with just the mandatory user inputs

vcd_cli/catalog.py
Added update function to catalog.py
=> Curt branch

vcd_cli/vapp.py
=> VCDA:168 & 169 : vcd-cli for Attach or Detach Independent Disk to/from a VM within a vApp

ChangeLog, vcd_cli/vapp.py
- add disk to vm
- minor cosmetic changes
=> add disk to vm

vcd_cli/catalog.py, vcd_cli/disk.py, vcd_cli/role.py, vcd_cli/user.py, vcd_cli/utils.py, vcd_cli/vapp.py
Ran flake8 to make sure that there are no hanging references after the refactoring.
Ran vcd login, vcd org list, vcd org info, vcd catalog info etc. to make sure that the basic commands are all working fine.
=> Refactoring code to honor the movement of is_admin field and related logic in pyvcloud's org.py

vcd_cli/org.py, vcd_cli/user.py
1. Enable/Disable Org which is already created (via 'vcd org update <org_name>' command)
2. Add new option '--enable' to enable org during creation.
3. Enable/disable user which was already created. (via 'vcd user update <user_name>' command)
Review complete:
https://reviewable.io/reviews/anusuyar/vcd-cli/4
=> Enable/Disable Org, User. Add --enable option for create org.

vcd_cli/user.py
Review complete: https://reviewable.io/reviews/anusuyar/vcd-cli/5
=> Changing the args format to pass param name and value.

vcd_cli/org.py, vcd_cli/user.py
Review done: https://reviewable.io/reviews/anusuyar/vcd-cli/6
=>  Removed org_name in the update_org

vcd_cli/role.py
> vcd role create diskRole2 diskRole_description 'Disk: View Properties' --org myOrg
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
property     value
--------------------------------------------------
Description  diskRole_description
href         https://127.0.0.1:8443/api/admin/org/9d6f0dc6-ea1d-47a4-b9ea-60355b02b52c/role/7ff5735a-a737-4d8d-83a4-c57eed063c49
id           7ff5735a-a737-4d8d-83a4-c57eed063c49
name         diskRole2
type         application/vnd.vmware.admin.role+xml
=> Create role in the specified Org or current Org

CONTRIBUTING.md
Restructured CONTRIBUTING.md to make it quick for experienced users but
also provide detailed instructions for new contributors, including those
for whom this is their first Github contribution.  Changes include
reordering to get most critical information in front and create a
soup-to-nuts example that illustrates Git commands and conventions to
follow for a successful pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/142)
=> Improve CONTRIBUTING.md to make it more informative

requirements.txt, test-requirements.txt, vcd_cli/disk.py, vcd_cli/login.py, vcd_cli/netpool.py, vcd_cli/org.py, vcd_cli/profile.py, vcd_cli/profiles.py, vcd_cli/pvdc.py, vcd_cli/search.py, vcd_cli/user.py, vcd_cli/utils.py, vcd_cli/vapp.py, vcd_cli/vcd.py, vcd_cli/vdc.py
list of changes are listed in the commits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/139)
=> Create and delete OrgVDC and more

vcd_cli/catalog.py, vcd_cli/utils.py
```
Implementing following commands
vcd catalog acl add <catalog-name> [subject:name:right]*
vcd catalog acl remove <catalog-name> [subject:name]*
vcd catalog acl share <catalog-name> --access-level ReadOnly
vcd catalog acl unshare <catalog-name>
vcd catalog acl list
vcd catalog acl info
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd catalog acl add Test2 'org:AnuOrg1:ReadOnly'  'user:user:FullControl'
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None
AnuOrg1              org             ReadOnly
user                 user            FullControl
C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl remove Test2 'org:AnuOrg1'
subject_name …
```
=> Implementing catalog update acl commands

vcd_cli/extension.py
- (Required) Short description of changes in the PR topic line
shows api filters configured for extension
- (Required) Detailed description of changes include tests and
documentation.  If the pull request contains multiple commits with 
detailed messages, refer to those instead
```
$ vcd system extension info cse
property                value
----------------------  ------------------------------------
enabled                 true
exchange                vcdext
filter_1                /api/cse/.*/.*
filter_2                /api/cse
filter_3                /api/cse/.*
id                      eccf0753-58d1-454e-8ed4-94f8872002d6
isAuthorizationEnabled  false
name                    cse
namespace               cse
priority …
```
=> VCDA-419 retrieve api filter for extension

docs/_layouts/default.html, docs/configuration.md, docs/install.md, test-requirements.txt, tox.ini, vcd_cli/catalog.py, vcd_cli/disk.py, vcd_cli/role.py, vcd_cli/utils.py, vcd_cli/vapp.py, vcd_cli/vcd.py
- (Required) Short description of changes in the PR topic line
- power-off, undeploy, delete VM(s)
- minor PEP8 compliance changes
- documentation improvements
- new documentation not generated yet
- vapp examples:
```
vcd vapp power-off vapp1 vm1 vm2
Power off vm1 and vm2 of vapp1.
vcd vapp undeploy vapp1 vm1 vm2
Undeploy vm1 and vm2 of vapp1.
vcd vapp delete vapp1 vm1 vm2
Delete vm1 and vm2 from vapp1.
```
- (Required) Detailed description of changes include tests and
documentation.  If the pull request contains multiple commits with 
detailed messages, refer to those instead
see commit messages
- (Optional) Names of reviewers using @ sign + name
@rocknes @sahithi @anusuyar @sompa
--- …
=> VCDA-362,343,408 Power-off, undeploy, delete VM(s)

vcd_cli/extension.py, vcd_cli/utils.py, vcd_cli/vc.py, vcd_cli/vcd.py, vcd_cli/vm.py
- refactored Extension to APIExtension
- improved stdout
- added new commands vc to list vCenters and get vCenter info
- renamed list vms to avoid use of reserved word
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/163)
=> VCDA-354: CSE support multiple vCenters

vcd_cli/catalog.py, vcd_cli/user.py, vcd_cli/utils.py, vcd_cli/vapp.py, vcd_cli/vdc.py
Implementing commands to update acl of vdc and vapp.
Implementing add, remove, share, unshare, list acl commands for vdc and vapp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/160)
=>  Implementing commands to update acl of vdc and vapp

vcd_cli/utils.py
- more meaningfull error messages when session invalid
- nicer display of tables when cells contain lists
- PEP8 formatting of the updated files only
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/162)
=> VCDA-248 error handling on invalid session

vcd_cli/right.py, vcd_cli/role.py
1. Command to add new rights to a given organization.
2. Command to remove new rights from a given organization.
3. Fixed a bug in the existing command 'list-rights'. It always listed all rights available in the System instead of set of rights associated with any given organization. Fixed it as part of this change-set.
4. Added Click-remove-confirmation to one of the existing commands of role.
**Command output:**
>vcd right add 'vCenter: View' -o myOrg
>Rights added to the Org 'myOrg'
>vcd right remove 'vCenter: View' -o myOrg
>Are you sure you want to remove rights from the organization? [y/N]: y
>Rights removed from the Org 'myOrg'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add or remove rights from organization

ChangeLog, tests/cleanup.sh, tests/tenant-onboard.sh, tests/tenant-operations.sh, vcd_cli/catalog.py, vcd_cli/extension.py, vcd_cli/task.py, vcd_cli/utils.py
- fixes --no-wait option
- list tasks by status
- wait for task by id
- process MissingRecordException
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/167)
=> VCDA-451: work with pending tasks

.travis.yml
- updated travis CI file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/171)
=> Updated travis ci

vcd_cli/org.py
Most of the changes required  to make the above mentioned commands case insensitive has been implemented in pyvcloud. This commit fixes the case sensitivity issue for "vcd org use" and "vcd org info" command, specifically in determination of the boolean values for, whether the org being worked on is in use or if it's the currently logged in org.
Manually ran the following commands to verify the change:
(vcd-cli) C:\code\vcd-cli\vcd_cli>vcd login 10.150.198.172 system administrator -i -w
Password:
administrator logged in, org: 'system', vdc: ''
(vcd-cli) C:\code\vcd-cli\vcd_cli>vcd org list
in_use    logged_in    name
--------  -----------  --------
True      True         System
False     False        testorg1
False     False        abc
(vcd-cli) C:\code\vcd-cli\vcd_cli>vcd org use …
=> VCDA-370 & VCDA-475: Making vcd org [info/update/use/delete/list] and vcd user [update/delete] case insensitive

vcd_cli/user.py
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd user list -o AnuOrg
deployedVMQuota    deployedVMQuotaRank  fullName    identityProviderType    isEnabled    isLdapUser    name        numberOfDeployedVMs    numberOfStoredVMs    storedVMQuota    storedVMQuotaRank
-----------------  ---------------------  ----------  ----------------------  -----------  ------------  --------  ---------------------  -------------------  ---------------  -------------------
0                     -1              INTEGRATED              true         false         user1                         0                    0                0                   -1
0                     -1              INTEGRATED              true         false         user2                         0 …
=> VCDA-473: Implement vcd user list command

vcd_cli/right.py
- Fixing bugs in rights
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/180)
=> Fixing cosmetic bugs in rights

vcd_cli/extension.py, vcd_cli/pvdc.py, vcd_cli/user.py, vcd_cli/vapp.py
- api extension commands now consider both name and namespace
- automated re-formatted code in pvdc.py, user.py and vapp.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/183)
=> VCDA-474: consider name and namespace in api extension

vcd_cli/pvdc.py
Added create PVDC
Reviewers: @pacogomez @sahithi @anusuyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/182)
=> VDP-1205, VCDA-462: added create PVDC to pvdc.py

vcd_cli/pvdc.py, vcd_cli/vc.py
VDP-1375, VCDA-504: Attach VC
- Reviewers: @sompa @anusuyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/194)
=> VDP-1375, VCDA-504: Attach VC

docs/install.md
Added latest information on setting Python path as well as updating pbr
to ensure pip3 install works.
Reviewers: @sompa, @sahithi, @rocknes, @anusuyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/198)
=> VCDA-502: Add additional Mac OS X install notes

vcd_cli/pvdc.py, vcd_cli/vc.py
- added wait for async commands to complete (attach vc and create pvdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/208)
=> added wait for async commands to complete (attach vc and create pvdc)

vcd_cli/pvdc.py, vcd_cli/vc.py
- Added optional root_folder parameter to attach VC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/212)
=> [VCDA-605] Added optional root_folder parameter to attach VC

vcd_cli/utils.py, vcd_cli/vdc.py
the build error is get fixed once pyvcloud changes are checked-in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/213)
=> Changes in vcd-cli related to the Exception Handling changes in pyvcloud

vcd_cli/pvdc.py
- added support for nsxt manager (new optional parameter for create pvdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/214)
=> [VCDA-606] added support for nsxt manager (new optional parameter for create pvdc)

vcd_cli/nsxt.py, vcd_cli/vcd.py
- [VDP-1661, VCDA-619] Added register, list, and unregister NSX-T Managers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/223)
=> [VDP-1661, VCDA-619] Added register, list, and unregister NSX-T Managers

AUTHORS, ChangeLog
* Merging auto generated files during release of vcd-cliv19.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/224)
=> Updated AUTHORS and ChangeLog for v20.3.0

vcd_cli/login.py, vcd_cli/org.py, vcd_cli/vdc.py
* Made required changes to consumers of pyvcloud.vcd.Client.get_org(), pyvcloud.vcd.Client.get_org_by_name() and pyvcloud.vcd.Client.get_org_list() to handle the changes made to their return values (and types).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/226)
=> [VCDA-584] Handled fallout of making changes to org related methods

vcd_cli/vc.py
[VDP-1665, VCDA-642] Implemented enable, disable, detach VC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/227)
=> [VDP-1665, VCDA-642] Implemented enable, disable, detach VC

vcd_cli/pvdc.py
[VDP-1663, VCDA-696]: Implement add, delete ResourcePool from a PVDC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/236)
=> [VDP-1663, VCDA-696]: Implement add, delete ResourcePool from a PVDC

vcd_cli/pvdc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/238)
=> BUG FIX: Add to docstring about current RP name limitation (basenames must be unique) and rename functions from add/delete to attach/detach

system_tests/pvdc_tests.py, vcd_cli/pvdc.py
- added support for add and delete storage profiles to vcd-cli
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/264)
=> [VDP-2171]: added support for add and delete storage profiles to vcd-cli

system_tests/extnet_tests.py, vcd_cli/network.py
VP-1152:[VCD-CLI] Add subnet to external network
This CLN contains changes related to adding subnet in existing external
network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/268)
=> VP-1152:[VCD-CLI] Add subnet to external network

system_tests/gateway_tests.py, vcd_cli/gateway.py
Added redeploy function to gateway.py and corresponding test case.
Testing done: ran gateway_tests successfully.
To help us process your pull request efficiently, please include:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/271)
=> VP-1161 : Redploy edge gateway.

system_tests/gateway_tests.py, vcd_cli/gateway.py
Added a function sync_syslog_settings to gateway.py and corresponding test cases.
Testing done: ran gateway_tests successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/272)
=> VP-1163: Synchronize syslog server settings of a gateway.

system_tests/gateway_tests.py, vcd_cli/gateway.py
VP-1293:List edge gateway's Configure IP Settings
Lists the  edge gateway's Configure IP Settings 
Changes:
gateway.py
gateway_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/275)
=> VP-1293:List edge gateway's Configure IP Settings

system_tests/extnet_tests.py, vcd_cli/network.py
[VCD-CLI] Enable a subnet in external network.
The code contains vcd-cli for enable subnet in external network and test
case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/280)
=> VP-1238: [VCD-CLI] Enable a subnet in external network

system_tests/extnet_tests.py, vcd_cli/network.py
[VCD-CLI] Add an IP range to a subnet in external network
This code base has both functionality and test case.
=> VP1242: [VCD-CLI] Add an IP range to a subnet in external network

system_tests/base_config.yaml, system_tests/extnet_tests.py, system_tests/helpers/portgroup_helper.py, vcd_cli/network.py
VP 1260: [VCD-CLI] Detach port groups from an external network
[VCD-CLI] Detach port groups from an external network
This code has functionality and test case for detach port group.
To help us process your pull request efficiently, please include:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/286)
=> Detach port group

system_tests/vdc_network_tests.py, vcd_cli/network.py
vcd network routed edit name --name name1 --description new_des --shared-enabled
Testing Done: Written new test in VdcNetworkTests class. Executed complete VdcNetworkTests for testing and found to be successfull.
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/291)
=> [VP-1358]Edit routed network includes(Edit Name, Share network with other VDCs in this organization)

system_tests/base_config.yaml, system_tests/nat_rule_tests.py, vcd_cli/gateway.py, vcd_cli/nat_rule.py, vcd_cli/vcd.py
CLI command to add SNAT and DNAT rule.
Two separate commands to add SNAT and DNAT rule.
Note:
After delete nat rule done we will remove the skip.
test_0098_teardown
Testing Done:
Below tests passed
test_0010_add_snat_rule
test_0020_add_snat_rule
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/312)
=> VP-1585: Add SNAT and DNAT rule

system_tests/firewall_rule_tests.py, vcd_cli/firewall_rule.py, vcd_cli/vcd.py
New command is added to add new firewall rule.
vcd gateway services firewall create gateway1 --name rule1 --action accept --type User --enabled --logging-enabled
Testing Done:Added new test method and executed sucessfully
@guptaankit52 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/314)
=> [VP-1537] Provided CLI command for Add Firewall Rule

system_tests/nat_rule_tests.py, vcd_cli/nat_rule.py
List NAT Rules
List the NAT rules on an gateway
Testing Done:
Added the below test
test_0025_list_nat_rules
status: passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/315)
=> VP-1591: List NAT Rules

system_tests/firewall_rule_tests.py, vcd_cli/firewall_rule.py
VP-1543:[VCDCLI] List Firewall rules and list user defined rules
VCDCLI : User would be able to perform operation list of firewall rule on gateway 
vcd gateway services firewall list gateway_name
output:
ID          | name | ruleType
131076  | firewall | internal_high
Testing Done:
Added test_0001_list_firewall_rules method to firewall_rule_tests.py
=> VP-1543:[VCDCLI] List Firewall rules and list user defined rules

system_tests/base_config.yaml, system_tests/gateway_tests.py, vcd_cli/gateway.py
Fixed gateway related failing test cases
There are few test cases which are failing. I modified to execute the test case using locally created gateway.
Skipping the convert to advanced gateway if API version is greater and equeal to API version 32.0.
For failed test case reference: https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-vcdcli-1.0-STF/11/consoleFull
As of now, test_0016_edit_config_ip_settings is failing sporadically. I will look into if it fails again after these fixes.
Testing Done: Executed them locally and found to working fine.
@shashim22 @pandeys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/326)
=> Test failure

system_tests/firewall_rule_tests.py, vcd_cli/firewall_rule.py
Provided support for edit firewall rule
User can edit source and destination of the firewall rule.
Command: vcd gateway services firewall update test_gateway1 rule_id
--destination ExtNw:gatewayinterface
--destination ExtNw1:gatewayinterface
--destination vm1:virtualmachine
--source ExtNw:gatewayinterface
--source 10.20.3.2:ip
Testing Done: Added test case and executed them successfully.
@shashim22 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/333)
=> Edit firewall

system_tests/static_route_tests.py, vcd_cli/static_route.py
Vcd-cli commands to update the all fields of static route and delete the same.
Testing done:
Added below tests
test_0030_update_static_route : passed
test_0098_teardown(to delete static route): passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/331)
=> VP-1607-1609: Edit and Delete the static route

system_tests/extnet_tests.py, system_tests/ipsec_vpn_tests.py, vcd_cli/ipsec_vpn.py, vcd_cli/network.py, vcd_cli/vcd.py
VP-1709,1711,1716,1718,1722,1728:Add,delete ,activation status, logging of IPsec VPN
VP-1709:[VCDCLI] Enable Application Status
VP-1711:[VCDCLI] Info Activation Status
VP-1716:[VCDCLI] Set Info level for logging:Global Configuration
VP-1718:[VCDCLI] Enable Logging Settings
VP-1722:[VCDCLI] Add IPsec VPN Sites
VP-1728:[VCDCLI] Delete IPsec VPN Sites
This CLN contains above functionalities and their test cases.
Testing Done: Executed the complete test class successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/338)
=> Add delete ipsec

system_tests/nat_rule_tests.py, vcd_cli/nat_rule.py
VCD-CLI command to get the nat rule info:
vcd gateway service nat info <gatewayName> <nat-ID>
Testing Done:
test_0030_info_nat_rule
status: passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/340)
=> VP:1595: Get the NAT Rule Info

system_tests/gateway_tests.py
Skiping test_0016_edit_config_ip_settings test case for gateway_tests.py
Its running for base gateway and not for other test gateway so skipping test case for now
=> Skiping test_0016_edit_config_ip_settings test case

system_tests/firewall_rule_tests.py, vcd_cli/firewall_rule.py
To improve typo error in code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/345)
=> Typo error firewall list

system_tests/run_system_tests.sh, vcd_cli/gateway.py
Modify the description of gateway edit command.
Skip the pvdc tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/351)
=> Modify cli-command details and skip test

system_tests/extnet_tests.py, vcd_cli/network.py
User can get the details of Extnwl network.
vcd network external info external-net1
Testing Done: Added new test case and executed successfully.
@guptaankit52 @kousgy123 @shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/350)
=> [VcdCli] Provided support for command Info of External network

README.md
Updating README.md to have Python 3.6 as required version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/353)
=> Update required version to Python 3.6

system_tests/vapp_tests.py, vcd_cli/network.py, vcd_cli/vapp.py
This CL adds new command update which takes name and description as parameters.
Added test case vapptests.test_0020_update_vapp for the same.
Testing done: Ran the test cases locally.
Executed the command locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/358)
=> VP-1402: add update command to change vApp name and description.

system_tests/nat_rule_tests.py, vcd_cli/nat_rule.py
vcd-cli command to edit SNAT and DNAT rule.
Commands:
create-dnat  create new DNAT rule
create-snat  create new SNAT rule
delete       Deletes the NAT rule
info         show NAT rule details
list         List all NAT rules on a gateway
update-dnat  update DNAT rule
update-snat  update SNAT rule
Testing Done:
Added below tests.
test_0035_update_snat_rule
test_0040_update_dnat_rule
Status : passed
- (Optional) @rajeshk2013 @shashim22
=> VP-1587: Edit a NAT Rule

requirements.txt, system_tests/main.py, system_tests/run_system_tests.sh
It will generate the JUnit test report at system_tests/test-reports folder.
Testing Done: https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-vcdcli-1.0-STF/44/console
=> Generate test report for CLI

system_tests/vm_tests.py, vcd_cli/vm.py
this CL adds delete-nic command to the vm command group.
added test case for the same in vm_tests
testing done: ran the command locally.
ran the test cases in dev setup successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/373)
=> VP-1804: vm: info command.

vcd_cli/org.py
VP-2153 : [2271719] : vcd-cli usage message bug in vcd org delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/391)
=> VP-2153 : [2271719] : vcd-cli usage message bug in vcd org delete

vcd_cli/org.py, vcd_cli/utils.py
Cli logger is changing to  rotating file handler logger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/392)
=> Logger change

vcd_cli/network.py, vcd_cli/routed.py
VP-2183 : List network for non admin user.
Adding a command to list org vdc network for non admin user.
To list network, following command can be used:
vcd network list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/395)
=> VP-2183 : List network for non admin user

system_tests/vapp_tests.py, vcd_cli/vapp.py
VP-2097 : [VcdCLI] Add to catalog.
Improve the Capture command for overwrite option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/399)
=> VP-2097 : [VcdCLI] Add to catalog

system_tests/run_system_tests.sh
VP-2397: [VCDCLI] Add missing test case classes to include in CI/CD
Testing Done:
These test cases will be executed with CI/CD run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/417)
=> VP-2397: [VCDCLI] Add missing test case classes to include in CI/CD

vcd_cli/login.py
VP-2373: Fix - CI/CD of VCD-CLI
Testing Done:
CI/CD will execute the test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/418)
=> VP-2373: Fix - CI/CD of VCD-CLI

system_tests/run_system_tests.sh
VP-2410: [VCD-CLI] Feature to add test files automatically.
This feature will enable developer not to add their new test files into
run_system_tests.sh manually. New test files will be picked
automatically. There is a provision for unstable tests which can be
enabled for particular test files manually.
Testing Done:
CI/CD will test the script in next run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/421)
=> VP-2410: [VCD-CLI] Feature to add test files automatically.

system_tests/vapp_tests.py, vcd_cli/vapp.py
VP-2103 : [VcdCLI] Move to vapp
This CLN contains move a vapp functionality and corresponding test case.
A vapp can move in different  org vdc contain by the org.
vcd vapp move vapp1 -v target_vdc_name
Testing Done:
Test method test_0090_move_to() is added in class vapp_tests.py and it is
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/419)
=> VP-2103 : [VcdCLI] Move to vapp

requirements.txt
PypiRelease
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/434)
=> PypiRelease

system_tests/vm_tests.py, vcd_cli/vm.py
VP-2069 : [VcdCLI] List Storage profiles.
This CLN contains a command for list storage profile of vm functionality and corresponding test case.
vcd vm list-storage-profile vapp1 vm1
Testing Done:
Test methods test_0200_list_storage_profile is added in class vm_tests.py and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/435)
=> VP-2069 : [VcdCLI] List Storage profiles

system_tests/vm_tests.py, vcd_cli/vm.py
[VcdCli] Check compliance
This CLN has VM functionality to check compliance. It calls VM POST API
for checkcompliance and give status based on returning task object. It
can be called from command line as :
vcd vm check-compliance vapp1 vm1
Testing Done:
Test method test_0230_check_compliance is added in vm_tests.py and it is
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/443)
=> VP-2601: [VcdCli] Check compliance

system_tests/gateway_tests.py, system_tests/nat_rule_tests.py, system_tests/org_tests.py, vcd_cli/gateway.py, vcd_cli/org.py
VP-2822: [PYSDK-VCDCLI] Bug fixes of CI/CD
This CLN contains fixes for test failures of Org and gateway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/469)
=> VP-2822: [PYSDK-VCDCLI] Bug fixes of CI/CD

system_tests/extnet_tests.py, system_tests/vm_tests.py
VP-2853: CLI CI/CD bug fix for vm_tests and ext_tests files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/474)
=> VP-2853: CLI CI/CD bug fix

system_tests/vapp_tests.py, vcd_cli/vapp.py
VP-2824: [VCDCLI]As a SDK user, I can create VM from scratch.
This CLN contains  create VM from scratch. These can be  called from command line as follows:  
vcd vapp add-vm-scratch vapp1 -vm vm1 -cn computer_name -d description
-os windows7_64Guest -cpu 2 -cps 2 -crm 2 -m 1024 -media pb1.iso -aae -deploy -power-on
Test methods test_0230_add_vm_scratch is added in vapp_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/483)
=> VP-2824: [VCDCLI]As a SDK user, I can create VM from scratch.

system_tests/role_tests.py, vcd_cli/role.py
Have not written system tests for this because i'm not sure which system test file contains testing for role commands. Could someone let me know where I should be writing system tests?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/478)
=> [VCDA-1091] Add role clone command

system_tests/extnet_tests.py, system_tests/gateway_tests.py
VP-2945: Test Failure in CI CD Stabilization barnch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/490)
=> VP-2945: Test Failure in CI CD Stabilization barnch

vcd_cli/vdc.py
VP-3051: [VCD-CLI] Fix bug in error statement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/493)
=> VP-3051: [VCD-CLI] Fix bug in error statement.

requirements.txt
Updating pyvcloud version to 21.0.1
=> Updating pyvcloud version to latest release version

requirements.txt, vcd_cli/utils.py
* Add `show_headers` option to prevent printing headers in stdout
* Testing done:
Called `stdout()` from cse with and without `show_headers` option set
@rocknes @sahithi @sakthisunda @ltimothy7 @ChintanShahVMware
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/vcd-cli/540)
=> Add option to avoid printing headers in stdout

requirements.txt
Update requirements.txt to consume the latest pyvcloud dev build
=> Consume pyvcloud 23.0.1.dev6

.travis.yml, tox.ini, vcd_cli/browsercookie/__init__.py, vcd_cli/ca_certificates.py, vcd_cli/catalog.py, vcd_cli/crl_certificates.py, vcd_cli/datastore.py, vcd_cli/dhcp_pool.py, vcd_cli/firewall_rule.py, vcd_cli/gateway.py, vcd_cli/ipsec_vpn.py, vcd_cli/nat_rule.py, vcd_cli/network.py, vcd_cli/org.py, vcd_cli/profile.py, vcd_cli/routed.py, vcd_cli/service_certificates.py, vcd_cli/static_route.py, vcd_cli/vapp.py, vcd_cli/vapp_network.py, vcd_cli/vapp_network_dhcp.py, vcd_cli/vapp_network_firewall.py, vcd_cli/vapp_network_nat.py, vcd_cli/vapp_network_static_route.py, vcd_cli/vc.py, vcd_cli/vdc.py, vcd_cli/vm.py
Fix flake8 errors
- @rajeshk2013
=> Fix flake8 errors

system_tests/ca_certificate_tests.py, system_tests/crl_certificate_tests.py, system_tests/dhcp_pool_test.py, system_tests/firewall_rule_tests.py, system_tests/ipsec_vpn_tests.py, system_tests/nat_rule_tests.py, system_tests/service_certificate_tests.py, system_tests/static_route_tests.py
Due to cyclic imports, these test classes were throwing following error:
ImportError: cannot import name 'gateway'
- @guptaankit52 @rajeshk2013
=> Fix unit test errors
